## 🔍 Indexing and Selecting Data

> Indexing in **Pandas** used to **identify, access, and modify subsets** of data in **Series** and **DataFrame** objects.

### Key Purposes of Indexing
- Provides **labels** (metadata) that identify and align data automatically.  
- Enables **intuitive selection** and manipulation of specific rows, columns, or values.

In [1]:
import pandas as pd
import numpy as np

## loc
 - Label-based

In [2]:
ser = pd.Series(range(5), index=list("abcde"))
ser

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [3]:
ser.loc[["a", "c", "e"]]

a    0
c    2
e    4
dtype: int64

## iloc

- Index-based

In [4]:
ser.iloc[[0, 2, 4]]

a    0
c    2
e    4
dtype: int64

## Slicing ranges

In [5]:
s = pd.Series(np.random.randn(10), index=pd.date_range("20230101", periods=10))
s

2023-01-01   -0.530628
2023-01-02   -1.820317
2023-01-03   -1.585004
2023-01-04    0.280641
2023-01-05   -0.193919
2023-01-06   -0.893971
2023-01-07   -0.761648
2023-01-08    0.062599
2023-01-09    0.134338
2023-01-10    0.678489
Freq: D, dtype: float64

In [6]:
# Get the first five values
s[:5]

2023-01-01   -0.530628
2023-01-02   -1.820317
2023-01-03   -1.585004
2023-01-04    0.280641
2023-01-05   -0.193919
Freq: D, dtype: float64

In [7]:
# Get every second value
s[::2]

2023-01-01   -0.530628
2023-01-03   -1.585004
2023-01-05   -0.193919
2023-01-07   -0.761648
2023-01-09    0.134338
Freq: 2D, dtype: float64

In [8]:
# Reverse the series
s[::-1]

2023-01-10    0.678489
2023-01-09    0.134338
2023-01-08    0.062599
2023-01-07   -0.761648
2023-01-06   -0.893971
2023-01-05   -0.193919
2023-01-04    0.280641
2023-01-03   -1.585004
2023-01-02   -1.820317
2023-01-01   -0.530628
Freq: -1D, dtype: float64

### Selection by callable

In [9]:
df_data = pd.DataFrame(np.random.randn(6, 4), index=list("abcdef"), columns=list("WXYZ"))
df_data

          W         X         Y         Z
a  1.098005  0.194467 -0.550175  2.486480
b  0.781245 -1.171605 -2.069343 -1.152900
c -0.646145  0.179469  1.266923  0.969127
d -0.594443  0.467542 -0.381230 -0.426029
e -0.731979  0.113632  0.145463  0.060677
f -0.882217  0.938214 -0.322923 -1.466142

In [10]:
df_data.loc[lambda df: df['W'] > 0, :]

          W         X         Y        Z
a  1.098005  0.194467 -0.550175  2.48648
b  0.781245 -1.171605 -2.069343 -1.15290

### Combining positional and label-based indexing

In [11]:
df_combined = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df_combined

   A  B
0  1  4
1  2  5
2  3  6

In [12]:
#  explicitly getting locations on the indexers, and using positional indexing to select things.
df_combined.loc[df_combined.index[[0, 2]], "A"]

0    1
2    3
Name: A, dtype: int64

In [13]:
# Accessing multiple indexers
df_combined.iloc[0:2, df_combined.columns.get_indexer(["A", "B"])]

   A  B
0  1  4
1  2  5

### Random Sample

In [17]:
s = pd.Series(np.random.randn(10))
s

0    0.015939
1    0.960050
2    0.793185
3   -1.545611
4   -0.112647
5    3.295231
6    0.251290
7   -0.742009
8   -1.206978
9    1.027627
dtype: float64

In [19]:
s.sample(5, replace=False)

9    1.027627
8   -1.206978
4   -0.112647
7   -0.742009
1    0.960050
dtype: float64

In [20]:
s.sample(5, replace=True)

8   -1.206978
3   -1.545611
4   -0.112647
6    0.251290
6    0.251290
dtype: float64