## 🔍 Indexing and Selecting Data

> Indexing in **Pandas** used to **identify, access, and modify subsets** of data in **Series** and **DataFrame** objects.

### Key Purposes of Indexing
- Provides **labels** (metadata) that identify and align data automatically.  
- Enables **intuitive selection** and manipulation of specific rows, columns, or values.

In [1]:
import pandas as pd
import numpy as np

## loc
 - Label-based

In [2]:
ser = pd.Series(range(5), index=list("abcde"))
ser

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [3]:
ser.loc[["a", "c", "e"]]

a    0
c    2
e    4
dtype: int64

## iloc

- Index-based

In [4]:
ser.iloc[[0, 2, 4]]

a    0
c    2
e    4
dtype: int64

## Slicing ranges

In [5]:
s = pd.Series(np.random.randn(10), index=pd.date_range("20230101", periods=10))
s

2023-01-01    1.693732
2023-01-02   -0.728776
2023-01-03   -0.863633
2023-01-04    1.296333
2023-01-05    0.610010
2023-01-06   -0.558379
2023-01-07    1.801299
2023-01-08   -2.220962
2023-01-09    0.565684
2023-01-10   -1.283699
Freq: D, dtype: float64

In [6]:
# Get the first five values
s[:5]

2023-01-01    1.693732
2023-01-02   -0.728776
2023-01-03   -0.863633
2023-01-04    1.296333
2023-01-05    0.610010
Freq: D, dtype: float64

In [7]:
# Get every second value
s[::2]

2023-01-01    1.693732
2023-01-03   -0.863633
2023-01-05    0.610010
2023-01-07    1.801299
2023-01-09    0.565684
Freq: 2D, dtype: float64

In [8]:
# Reverse the series
s[::-1]

2023-01-10   -1.283699
2023-01-09    0.565684
2023-01-08   -2.220962
2023-01-07    1.801299
2023-01-06   -0.558379
2023-01-05    0.610010
2023-01-04    1.296333
2023-01-03   -0.863633
2023-01-02   -0.728776
2023-01-01    1.693732
Freq: -1D, dtype: float64

### Selection by callable

In [9]:
df_data = pd.DataFrame(np.random.randn(6, 4), index=list("abcdef"), columns=list("WXYZ"))
df_data

          W         X         Y         Z
a  1.320486  0.623274 -0.072902  1.323399
b  1.067145  0.159076 -0.495939 -0.816492
c  1.272435  0.365354  0.233113 -0.608341
d  0.065929  2.302778 -0.622893 -1.613537
e -2.492163 -0.781564  1.507697 -0.818312
f -0.254023 -0.271151 -1.682306 -0.955472

In [10]:
df_data.loc[lambda df: df['W'] > 0, :]

          W         X         Y         Z
a  1.320486  0.623274 -0.072902  1.323399
b  1.067145  0.159076 -0.495939 -0.816492
c  1.272435  0.365354  0.233113 -0.608341
d  0.065929  2.302778 -0.622893 -1.613537

### Combining positional and label-based indexing

In [11]:
df_combined = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df_combined

   A  B
0  1  4
1  2  5
2  3  6

In [12]:
#  explicitly getting locations on the indexers, and using positional indexing to select things.
df_combined.loc[df_combined.index[[0, 2]], "A"]

0    1
2    3
Name: A, dtype: int64

In [13]:
# Accessing multiple indexers
df_combined.iloc[0:2, df_combined.columns.get_indexer(["A", "B"])]

   A  B
0  1  4
1  2  5

### Random Sample

In [14]:
s = pd.Series(np.random.randn(10))
s

0    0.047706
1    0.424103
2   -0.635635
3   -1.194097
4   -0.455210
5   -1.047972
6   -0.765235
7    0.536362
8    0.215073
9    1.239371
dtype: float64

In [15]:
s.sample(5, replace=False)

5   -1.047972
2   -0.635635
1    0.424103
8    0.215073
4   -0.455210
dtype: float64

In [16]:
s.sample(5, replace=True)

1    0.424103
6   -0.765235
1    0.424103
7    0.536362
2   -0.635635
dtype: float64

### Setting with enlargement

In [17]:
se = pd.Series(np.random.randn(3))
se

0   -1.905258
1    1.707414
2   -0.299660
dtype: float64

In [18]:
se[5] = 10
se

0    -1.905258
1     1.707414
2    -0.299660
5    10.000000
dtype: float64

In [19]:
dfi = pd.DataFrame(np.random.randn(3, 3), columns=list("ABC"))
dfi

          A         B         C
0  0.712392  1.549638  0.482945
1 -0.554784  1.109309  0.854997
2  0.889142 -1.186708 -0.030397

In [32]:
dfi.loc[:, 'D'] = dfi.loc[:, 'A'] 
dfi

          A         B         C         D
0  0.712392  1.549638  0.482945  0.712392
1 -0.554784  1.109309  0.854997 -0.554784
2  0.889142 -1.186708 -0.030397  0.889142

### Fast scalar value getting and setting

In [34]:
dfi.iat[0, 0] = 1
dfi

          A           B         C         D
0  1.000000  100.000000  0.482945  0.712392
1 -0.554784    1.109309  0.854997 -0.554784
2  0.889142   -1.186708 -0.030397  0.889142

In [35]:
dfi.at[0, "C"] = 101
dfi

          A           B           C         D
0  1.000000  100.000000  101.000000  0.712392
1 -0.554784    1.109309    0.854997 -0.554784
2  0.889142   -1.186708   -0.030397  0.889142