## 🔍 Indexing and Selecting Data

> Indexing in **Pandas** used to **identify, access, and modify subsets** of data in **Series** and **DataFrame** objects.

### Key Purposes of Indexing
- Provides **labels** (metadata) that identify and align data automatically.  
- Enables **intuitive selection** and manipulation of specific rows, columns, or values.

In [1]:
import pandas as pd
import numpy as np

## loc
 - Label-based

In [2]:
ser = pd.Series(range(5), index=list("abcde"))
ser

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [3]:
ser.loc[["a", "c", "e"]]

a    0
c    2
e    4
dtype: int64

## iloc

- Index-based

In [4]:
ser.iloc[[0, 2, 4]]

a    0
c    2
e    4
dtype: int64

## Slicing ranges

In [5]:
s = pd.Series(np.random.randn(10), index=pd.date_range("20230101", periods=10))
s

2023-01-01   -1.074683
2023-01-02    0.007016
2023-01-03    0.851089
2023-01-04   -0.724286
2023-01-05    0.521763
2023-01-06   -0.018933
2023-01-07   -1.321448
2023-01-08   -0.471508
2023-01-09    0.706968
2023-01-10    0.210708
Freq: D, dtype: float64

In [6]:
# Get the first five values
s[:5]

2023-01-01   -1.074683
2023-01-02    0.007016
2023-01-03    0.851089
2023-01-04   -0.724286
2023-01-05    0.521763
Freq: D, dtype: float64

In [7]:
# Get every second value
s[::2]

2023-01-01   -1.074683
2023-01-03    0.851089
2023-01-05    0.521763
2023-01-07   -1.321448
2023-01-09    0.706968
Freq: 2D, dtype: float64

In [8]:
# Reverse the series
s[::-1]

2023-01-10    0.210708
2023-01-09    0.706968
2023-01-08   -0.471508
2023-01-07   -1.321448
2023-01-06   -0.018933
2023-01-05    0.521763
2023-01-04   -0.724286
2023-01-03    0.851089
2023-01-02    0.007016
2023-01-01   -1.074683
Freq: -1D, dtype: float64

### Selection by callable

In [9]:
df_data = pd.DataFrame(np.random.randn(6, 4), index=list("abcdef"), columns=list("WXYZ"))
df_data

          W         X         Y         Z
a  0.093565  0.238200  1.066158 -1.559709
b  1.116269  0.051288 -0.040258  0.570737
c -1.213426 -0.720893 -0.016054 -0.056382
d  0.199699 -0.718490  1.065278 -1.440858
e -2.400858  1.933208 -0.446702 -1.007209
f -0.791209 -2.180797  1.315469  1.072571

In [10]:
df_data.loc[lambda df: df['W'] > 0, :]

          W         X         Y         Z
a  0.093565  0.238200  1.066158 -1.559709
b  1.116269  0.051288 -0.040258  0.570737
d  0.199699 -0.718490  1.065278 -1.440858

### Combining positional and label-based indexing

In [11]:
df_combined = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df_combined

   A  B
0  1  4
1  2  5
2  3  6

In [12]:
#  explicitly getting locations on the indexers, and using positional indexing to select things.
df_combined.loc[df_combined.index[[0, 2]], "A"]

0    1
2    3
Name: A, dtype: int64

In [13]:
# Accessing multiple indexers
df_combined.iloc[0:2, df_combined.columns.get_indexer(["A", "B"])]

   A  B
0  1  4
1  2  5

### Random Sample

In [14]:
s = pd.Series(np.random.randn(10))
s

0   -0.892155
1    0.008404
2   -1.083542
3   -1.373445
4    2.120657
5    0.972317
6   -0.954409
7   -0.187199
8   -0.516345
9   -0.539848
dtype: float64

In [15]:
s.sample(5, replace=False)

6   -0.954409
3   -1.373445
9   -0.539848
7   -0.187199
8   -0.516345
dtype: float64

In [16]:
s.sample(5, replace=True)

0   -0.892155
1    0.008404
6   -0.954409
8   -0.516345
0   -0.892155
dtype: float64

### Setting with enlargement

In [20]:
se = pd.Series(np.random.randn(3))
se

0   -1.686420
1    0.279115
2    0.890288
dtype: float64

In [22]:
se[5] = 10
se

0    -1.686420
1     0.279115
2     0.890288
5    10.000000
dtype: float64

In [31]:
dfi = pd.DataFrame(np.random.randn(3, 3), columns=list("ABC"))
dfi

          A         B         C
0  0.022115  0.346568  1.307355
1 -0.113381 -0.327085 -0.839369
2 -0.095879 -0.213927  0.993351

In [35]:
dfi.loc[:, 'D'] = dfi.loc[:, 'A'] 
dfi

          A         B         C         D
0  0.022115  0.346568  1.307355  0.022115
1 -0.113381 -0.327085 -0.839369 -0.113381
2 -0.095879 -0.213927  0.993351 -0.095879