## 🔍 Indexing and Selecting Data

> Indexing in **Pandas** used to **identify, access, and modify subsets** of data in **Series** and **DataFrame** objects.

### Key Purposes of Indexing
- Provides **labels** (metadata) that identify and align data automatically.  
- Enables **intuitive selection** and manipulation of specific rows, columns, or values.

In [1]:
import pandas as pd
import numpy as np

## loc
 - Label-based

In [2]:
ser = pd.Series(range(5), index=list("abcde"))
ser

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [3]:
ser.loc[["a", "c", "e"]]

a    0
c    2
e    4
dtype: int64

## iloc

- Index-based

In [4]:
ser.iloc[[0, 2, 4]]

a    0
c    2
e    4
dtype: int64

## Slicing ranges

In [5]:
s = pd.Series(np.random.randn(10), index=pd.date_range("20230101", periods=10))
s

2023-01-01    0.839413
2023-01-02   -3.171733
2023-01-03    0.585102
2023-01-04   -1.366397
2023-01-05    0.631714
2023-01-06   -0.309880
2023-01-07   -1.089241
2023-01-08   -0.784914
2023-01-09    1.317962
2023-01-10   -0.629883
Freq: D, dtype: float64

In [6]:
# Get the first five values
s[:5]

2023-01-01    0.839413
2023-01-02   -3.171733
2023-01-03    0.585102
2023-01-04   -1.366397
2023-01-05    0.631714
Freq: D, dtype: float64

In [7]:
# Get every second value
s[::2]

2023-01-01    0.839413
2023-01-03    0.585102
2023-01-05    0.631714
2023-01-07   -1.089241
2023-01-09    1.317962
Freq: 2D, dtype: float64

In [8]:
# Reverse the series
s[::-1]

2023-01-10   -0.629883
2023-01-09    1.317962
2023-01-08   -0.784914
2023-01-07   -1.089241
2023-01-06   -0.309880
2023-01-05    0.631714
2023-01-04   -1.366397
2023-01-03    0.585102
2023-01-02   -3.171733
2023-01-01    0.839413
Freq: -1D, dtype: float64

### Selection by callable

In [9]:
df_data = pd.DataFrame(np.random.randn(6, 4), index=list("abcdef"), columns=list("WXYZ"))
df_data

          W         X         Y         Z
a -0.614711 -0.495102  0.889057 -1.261483
b -0.572310  0.036151  0.445368 -1.333114
c -0.989090  0.622781  1.507328  0.617863
d -0.823804  0.746385  0.100001  0.117209
e  0.884798 -1.209064 -1.110878  0.495273
f  0.091517  0.036530 -0.168232  0.982062

In [10]:
df_data.loc[lambda df: df['W'] > 0, :]

          W         X         Y         Z
e  0.884798 -1.209064 -1.110878  0.495273
f  0.091517  0.036530 -0.168232  0.982062

### Combining positional and label-based indexing

In [11]:
df_combined = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df_combined

   A  B
0  1  4
1  2  5
2  3  6

In [ ]:
#  explicitly getting locations on the indexers, and using positional indexing to select things.
df_combined.loc[df_combined.index[[0, 2]], "A"]

0    1
2    3
Name: A, dtype: int64

In [ ]:
# Accessing multiple indexers
df_combined.iloc[0:2, df_combined.columns.get_indexer(["A", "B"])]

   A  B
0  1  4
1  2  5