## 🔍 Indexing and Selecting Data

> Indexing in **Pandas** used to **identify, access, and modify subsets** of data in **Series** and **DataFrame** objects.

### Key Purposes of Indexing
- Provides **labels** (metadata) that identify and align data automatically.  
- Enables **intuitive selection** and manipulation of specific rows, columns, or values.

In [1]:
import pandas as pd
import numpy as np

## loc
 - Label-based

In [2]:
ser = pd.Series(range(5), index=list("abcde"))
ser

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [3]:
ser.loc[["a", "c", "e"]]

a    0
c    2
e    4
dtype: int64

## iloc

- Index-based

In [4]:
ser.iloc[[0, 2, 4]]

a    0
c    2
e    4
dtype: int64

## Slicing ranges

In [5]:
s = pd.Series(np.random.randn(10), index=pd.date_range("20230101", periods=10))
s

2023-01-01    0.048662
2023-01-02    0.251052
2023-01-03   -0.783535
2023-01-04   -0.144367
2023-01-05   -0.206498
2023-01-06   -0.747245
2023-01-07    0.375383
2023-01-08   -0.613268
2023-01-09   -1.649781
2023-01-10    0.144990
Freq: D, dtype: float64

In [6]:
# Get the first five values
s[:5]

2023-01-01    0.048662
2023-01-02    0.251052
2023-01-03   -0.783535
2023-01-04   -0.144367
2023-01-05   -0.206498
Freq: D, dtype: float64

In [7]:
# Get every second value
s[::2]

2023-01-01    0.048662
2023-01-03   -0.783535
2023-01-05   -0.206498
2023-01-07    0.375383
2023-01-09   -1.649781
Freq: 2D, dtype: float64

In [8]:
# Reverse the series
s[::-1]

2023-01-10    0.144990
2023-01-09   -1.649781
2023-01-08   -0.613268
2023-01-07    0.375383
2023-01-06   -0.747245
2023-01-05   -0.206498
2023-01-04   -0.144367
2023-01-03   -0.783535
2023-01-02    0.251052
2023-01-01    0.048662
Freq: -1D, dtype: float64

### Selection by callable

In [32]:
df_data = pd.DataFrame(np.random.randn(6, 4), index=list("abcdef"), columns=list("WXYZ"))
df_data

          W         X         Y         Z
a -1.538897 -1.808888 -0.682774 -1.275628
b  0.906254 -0.488839  1.136315  1.216809
c  0.361703  0.616664 -0.044585 -0.438137
d -0.540934 -1.645947 -1.571783 -0.932109
e -0.546054 -1.015917 -0.833259  0.651533
f  0.686349 -1.843801 -1.076285  0.478431

In [33]:
df_data.loc[lambda df: df['W'] > 0, :]

          W         X         Y         Z
b  0.906254 -0.488839  1.136315  1.216809
c  0.361703  0.616664 -0.044585 -0.438137
f  0.686349 -1.843801 -1.076285  0.478431