##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -0.240431
1    2.537521
2   -0.984553
3   -0.434078
4    1.379660
5    0.850190
6   -0.594428
7    0.176174
8    1.213758
9    0.085333
dtype: float64

In [3]:
# Head
long_series.head()

0   -0.240431
1    2.537521
2   -0.984553
3   -0.434078
4    1.379660
dtype: float64

In [4]:
# Tail
long_series.tail()

5    0.850190
6   -0.594428
7    0.176174
8    1.213758
9    0.085333
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01 -1.634710 -0.801706 -1.652735  1.041241
2023-01-02  0.057983  1.745720  0.550407 -0.242976
2023-01-03 -2.382575 -0.360210  1.121426  0.893988
2023-01-04 -0.595574 -0.383947 -0.634511 -0.604827
2023-01-05  0.433814 -0.529523  0.243776 -0.718836
2023-01-06  1.348389 -1.175793  0.165583  0.401515
2023-01-07  0.235977  1.497953  0.126902 -2.215353
2023-01-08  1.832561 -0.382401 -0.618224 -0.028351
2023-01-09 -1.531192  0.309384 -0.289462 -2.301269
2023-01-10 -0.276197  0.641052  0.881634  0.410520

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01 -1.634710 -0.801706 -1.652735  1.041241
2023-01-02  0.057983  1.745720  0.550407 -0.242976
2023-01-03 -2.382575 -0.360210  1.121426  0.893988
2023-01-04 -0.595574 -0.383947 -0.634511 -0.604827
2023-01-05  0.433814 -0.529523  0.243776 -0.718836
2023-01-06  1.348389 -1.175793  0.165583  0.401515
2023-01-07  0.235977  1.497953  0.126902 -2.215353
2023-01-08  1.832561 -0.382401 -0.618224 -0.028351
2023-01-09 -1.531192  0.309384 -0.289462 -2.301269
2023-01-10 -0.276197  0.641052  0.881634  0.410520

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[-1.63470975, -0.80170569, -1.65273517,  1.04124066],
       [ 0.05798337,  1.74572002,  0.55040721, -0.24297562],
       [-2.38257545, -0.36020967,  1.12142587,  0.89398789],
       [-0.59557436, -0.38394701, -0.63451124, -0.60482703],
       [ 0.43381415, -0.5295226 ,  0.24377576, -0.71883566],
       [ 1.34838886, -1.17579272,  0.16558335,  0.40151519],
       [ 0.2359773 ,  1.49795293,  0.12690207, -2.21535324],
       [ 1.83256089, -0.38240073, -0.61822381, -0.02835127],
       [-1.53119168,  0.30938352, -0.28946206, -2.30126898],
       [-0.27619653,  0.64105241,  0.88163359,  0.41052028]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  6.0  6.0      6
b  6.0  0.0      0
c  1.0  2.0      1
d  NaN  NaN      2

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      1.0
two      2.0
three    1.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a  5.0  4.0    5.0
b  5.0 -2.0   -1.0
c  0.0  0.0    0.0
d  NaN  NaN    1.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01 -1.634710 -0.801706 -1.652735  1.041241
2023-01-02  0.057983  1.745720  0.550407 -0.242976
2023-01-03 -2.382575 -0.360210       NaN  0.893988
2023-01-04 -0.595574 -0.383947 -0.634511 -0.604827
2023-01-05  0.433814 -0.529523  0.243776 -0.718836

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01 -1.634710 -0.801706 -1.652735  1.041241
2023-01-02  0.057983  1.745720  0.550407 -0.242976
2023-01-03 -2.382575 -0.360210       NaN  0.893988
2023-01-04 -0.595574 -0.383947 -0.634511 -0.604827
2023-01-05  0.433814 -0.529523  0.243776 -0.718836

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0 -0.982462  1.224868  0.216792
1 -0.659676  0.437171 -0.126693
2 -0.469466  0.457029  0.914953
3 -0.528197 -0.459453  1.025080
4  0.961652 -0.418699  0.852939

In [17]:
df_max_min.idxmax(axis=0)

A    4
B    0
C    3
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    A
1    A
2    A
3    A
4    B
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([0, 3, 5, 1, 6, 2, 4, 0, 6, 2, 6, 1, 4, 0, 5, 6, 3, 5, 0, 5, 4, 6,
       0, 4, 4, 3, 0, 0, 2, 2, 1, 5, 1, 2, 0, 1, 2, 3, 6, 5, 3, 2, 4, 6,
       5, 1, 1, 5, 0, 1], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

0    9
5    8
1    8
2    7
6    7
4    6
3    5
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  3  4  2
1  3  3  0
2  2  0  2
3  1  3  1

In [28]:
df_apply.apply(np.sum, axis=0)

A     9
B    10
C     5
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    9    3    1
B   10    4    0
C    5    2    0

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [30]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  9  3  6
2000-01-02  5  8  5
2000-01-03  5  6  6
2000-01-04  8  8  7
2000-01-05  5  7  9
2000-01-06  5  8  3
2000-01-07  8  9  3
2000-01-08  7  7  4
2000-01-09  8  7  3
2000-01-10  6  6  6

In [31]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  3.000000  2  36
2000-01-02  2.236068  7  25
2000-01-03  2.236068  5  36
2000-01-04  2.828427  7  49
2000-01-05  2.236068  6  81
2000-01-06  2.236068  7   9
2000-01-07  2.828427  8   9
2000-01-08  2.645751  6  16
2000-01-09  2.828427  6   9
2000-01-10  2.449490  5  36

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [32]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a    1.086723
b    1.139228
c    0.928472
d   -0.170441
e   -0.396454
dtype: float64

In [33]:
s.reindex(["e", "d", "a"])

e   -0.396454
d   -0.170441
a    1.086723
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [34]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [35]:
ts

2000-01-03   -0.412675
2000-01-04   -0.438336
2000-01-05   -0.159742
2000-01-06   -0.408049
2000-01-07    0.453310
2000-01-08   -0.176904
2000-01-09    0.829559
2000-01-10    0.253932
Freq: D, dtype: float64

In [36]:
ts2.reindex(ts.index)

2000-01-03   -0.412675
2000-01-04         NaN
2000-01-05         NaN
2000-01-06   -0.408049
2000-01-07         NaN
2000-01-08         NaN
2000-01-09    0.829559
2000-01-10         NaN
Freq: D, dtype: float64

In [37]:
ts2.reindex(rng, method="nearest")

2000-01-03   -0.412675
2000-01-04   -0.412675
2000-01-05   -0.408049
2000-01-06   -0.408049
2000-01-07   -0.408049
2000-01-08    0.829559
2000-01-09    0.829559
2000-01-10    0.829559
Freq: D, dtype: float64

### Dropping Labels from an axis

In [38]:
df_drop = pd.DataFrame(np.random.randn(5, 7), columns=["A", "B", "C", "D", "E", "F", "G"])
df_drop

          A         B         C         D         E         F         G
0  0.777449  2.835355  1.188816 -0.245214  0.473776  1.555171  0.835305
1  0.148387  0.467361 -0.514302  1.082392  2.299176 -1.485007  1.962786
2  2.240808  0.462938 -1.081820  1.131071  0.791100  1.340530  0.218091
3 -0.645493 -1.831917 -0.243104 -0.182748 -0.439157  0.709176 -0.222147
4 -0.691257 -0.580644 -0.075883 -0.672519 -0.598325 -0.569004  0.695715

In [39]:
# Drop columns
df_drop_columns = df_drop.drop(["B", "D"], axis=1)
df_drop_columns

          A         C         E         F         G
0  0.777449  1.188816  0.473776  1.555171  0.835305
1  0.148387 -0.514302  2.299176 -1.485007  1.962786
2  2.240808 -1.081820  0.791100  1.340530  0.218091
3 -0.645493 -0.243104 -0.439157  0.709176 -0.222147
4 -0.691257 -0.075883 -0.598325 -0.569004  0.695715

In [40]:
# Drop rows
df_drop_rows = df_drop.drop([0, 1], axis=0)
df_drop_rows

          A         B         C         D         E         F         G
2  2.240808  0.462938 -1.081820  1.131071  0.791100  1.340530  0.218091
3 -0.645493 -1.831917 -0.243104 -0.182748 -0.439157  0.709176 -0.222147
4 -0.691257 -0.580644 -0.075883 -0.672519 -0.598325 -0.569004  0.695715

### iterrows

- It allows to iterate through the rows of a DataFrame as Series objects.

In [48]:
df_iterrows = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_iterrows

          A         B         C
0  1.638678  0.210888  0.074333
1  0.438711 -0.675304 -0.546958
2  0.183759 -1.074948 -0.322292
3  0.579286 -0.114203 -1.958154
4 -0.080165 -1.447859 -1.511493

In [50]:
for index, row in df_iterrows.iterrows():
    print(f"Index: {index}")
    print(f"Row A value: {row['A']}")
    print(f"Row B value: {row['B']}")
    print(f"Row C value: {row['C']}")
    print("-----")

Index: 0
Row A value: 1.6386779870044719
Row B value: 0.2108877916363079
Row C value: 0.07433262545838121
-----
Index: 1
Row A value: 0.4387114779733481
Row B value: -0.6753043928142413
Row C value: -0.5469582937472824
-----
Index: 2
Row A value: 0.18375941561092027
Row B value: -1.0749481627235056
Row C value: -0.3222917821832235
-----
Index: 3
Row A value: 0.5792860366045227
Row B value: -0.11420335929936719
Row C value: -1.9581537652559988
-----
Index: 4
Row A value: -0.08016465104806891
Row B value: -1.4478592647834645
Row C value: -1.511493094705536
-----