##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0    0.545331
1   -0.700172
2   -1.149627
3    1.895184
4    0.651290
5    0.684948
6    0.572207
7   -2.168347
8   -1.270514
9   -0.170848
dtype: float64

In [3]:
# Head
long_series.head()

0    0.545331
1   -0.700172
2   -1.149627
3    1.895184
4    0.651290
dtype: float64

In [4]:
# Tail
long_series.tail()

5    0.684948
6    0.572207
7   -2.168347
8   -1.270514
9   -0.170848
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01 -0.555977 -0.663046 -2.689476  1.647092
2023-01-02  0.157758  1.195262  1.018885  1.031946
2023-01-03 -0.877593  2.882178  0.411793  1.446435
2023-01-04  0.594904 -0.939638 -0.828740 -1.002942
2023-01-05  0.997025 -0.826968  0.253480  0.635712
2023-01-06 -2.122880  0.572202 -0.128318  1.024823
2023-01-07  0.427913  1.285661 -0.605399  0.045479
2023-01-08 -1.262620 -0.574722 -0.275754  0.462014
2023-01-09  0.537154 -0.398647  0.208225 -0.165839
2023-01-10  0.871995  2.333821  1.415516  1.877600

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01 -0.555977 -0.663046 -2.689476  1.647092
2023-01-02  0.157758  1.195262  1.018885  1.031946
2023-01-03 -0.877593  2.882178  0.411793  1.446435
2023-01-04  0.594904 -0.939638 -0.828740 -1.002942
2023-01-05  0.997025 -0.826968  0.253480  0.635712
2023-01-06 -2.122880  0.572202 -0.128318  1.024823
2023-01-07  0.427913  1.285661 -0.605399  0.045479
2023-01-08 -1.262620 -0.574722 -0.275754  0.462014
2023-01-09  0.537154 -0.398647  0.208225 -0.165839
2023-01-10  0.871995  2.333821  1.415516  1.877600

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[-0.5559772 , -0.66304562, -2.68947645,  1.64709161],
       [ 0.15775755,  1.19526226,  1.01888481,  1.03194551],
       [-0.87759333,  2.88217783,  0.41179276,  1.44643504],
       [ 0.5949039 , -0.93963842, -0.82874029, -1.00294197],
       [ 0.99702455, -0.82696816,  0.25347987,  0.63571186],
       [-2.12288037,  0.57220239, -0.12831845,  1.0248226 ],
       [ 0.42791314,  1.28566136, -0.60539924,  0.04547875],
       [-1.26261964, -0.57472219, -0.27575399,  0.46201445],
       [ 0.53715437, -0.3986468 ,  0.20822482, -0.16583936],
       [ 0.87199515,  2.33382056,  1.41551629,  1.87760012]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  8.0  0.0      6
b  2.0  2.0      8
c  9.0  9.0      0
d  NaN  NaN      6

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      9.0
two      9.0
three    0.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -1.0 -9.0    6.0
b -7.0 -7.0    8.0
c  0.0  0.0    0.0
d  NaN  NaN    6.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01 -0.555977 -0.663046 -2.689476  1.647092
2023-01-02  0.157758  1.195262  1.018885  1.031946
2023-01-03 -0.877593  2.882178       NaN  1.446435
2023-01-04  0.594904 -0.939638 -0.828740 -1.002942
2023-01-05  0.997025 -0.826968  0.253480  0.635712

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01 -0.555977 -0.663046 -2.689476  1.647092
2023-01-02  0.157758  1.195262  1.018885  1.031946
2023-01-03 -0.877593  2.882178       NaN  1.446435
2023-01-04  0.594904 -0.939638 -0.828740 -1.002942
2023-01-05  0.997025 -0.826968  0.253480  0.635712

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0 -1.285104  1.433528  2.353031
1  0.638227 -0.871248  1.386846
2  0.009584  1.471072  1.182070
3  0.074353 -0.285736  1.469386
4 -1.522607 -0.268991 -1.757704

In [17]:
df_max_min.idxmax(axis=0)

A    1
B    2
C    0
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    A
1    B
2    A
3    B
4    C
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([5, 0, 6, 0, 6, 0, 0, 1, 2, 0, 5, 6, 4, 4, 6, 6, 5, 5, 6, 1, 5, 1,
       6, 2, 6, 2, 6, 4, 1, 1, 0, 5, 1, 3, 3, 3, 0, 2, 5, 2, 6, 4, 6, 2,
       3, 6, 0, 4, 3, 6], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

6    13
0     8
5     7
1     6
2     6
4     5
3     5
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  2  1  0
1  3  3  1
2  0  2  4
3  1  2  1

In [28]:
df_apply.apply(np.sum, axis=0)

A    6
B    8
C    6
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    6    3    0
B    8    3    1
C    6    4    0

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [30]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  3  4  7
2000-01-02  9  5  6
2000-01-03  7  6  5
2000-01-04  6  6  8
2000-01-05  3  9  4
2000-01-06  5  8  8
2000-01-07  9  4  8
2000-01-08  7  3  4
2000-01-09  3  8  5
2000-01-10  5  3  9

In [31]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  1.732051  3  49
2000-01-02  3.000000  4  36
2000-01-03  2.645751  5  25
2000-01-04  2.449490  5  64
2000-01-05  1.732051  8  16
2000-01-06  2.236068  7  64
2000-01-07  3.000000  3  64
2000-01-08  2.645751  2  16
2000-01-09  1.732051  7  25
2000-01-10  2.236068  2  81

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [32]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a    1.318698
b    0.701524
c    0.013522
d   -0.774215
e    1.509860
dtype: float64

In [33]:
s.reindex(["e", "d", "a"])

e    1.509860
d   -0.774215
a    1.318698
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [34]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [35]:
ts

2000-01-03    0.942012
2000-01-04   -1.739430
2000-01-05    0.039771
2000-01-06   -0.844386
2000-01-07    0.365776
2000-01-08    1.997599
2000-01-09   -0.530751
2000-01-10    0.545248
Freq: D, dtype: float64

In [36]:
ts2.reindex(ts.index)

2000-01-03    0.942012
2000-01-04         NaN
2000-01-05         NaN
2000-01-06   -0.844386
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -0.530751
2000-01-10         NaN
Freq: D, dtype: float64

In [37]:
ts2.reindex(rng, method="nearest")

2000-01-03    0.942012
2000-01-04    0.942012
2000-01-05   -0.844386
2000-01-06   -0.844386
2000-01-07   -0.844386
2000-01-08   -0.530751
2000-01-09   -0.530751
2000-01-10   -0.530751
Freq: D, dtype: float64

### Dropping Labels from an axis

In [38]:
df_drop = pd.DataFrame(np.random.randn(5, 7), columns=["A", "B", "C", "D", "E", "F", "G"])
df_drop

          A         B         C         D         E         F         G
0  0.827363 -0.390734 -0.395402  0.186305 -2.035421  1.088220  0.216483
1 -0.745233 -1.452023 -0.367231  0.418539  0.418104  0.501659  0.205017
2 -0.159928 -1.413030  0.778857  0.044828 -0.729793 -2.213068  0.836170
3 -1.466165 -0.147145  0.939852  0.071958 -0.276953  0.940895 -2.045292
4  0.109133 -0.600886  1.473001  1.002607 -1.643116 -1.060425 -0.792009

In [39]:
# Drop columns
df_drop_columns = df_drop.drop(["B", "D"], axis=1)
df_drop_columns

          A         C         E         F         G
0  0.827363 -0.395402 -2.035421  1.088220  0.216483
1 -0.745233 -0.367231  0.418104  0.501659  0.205017
2 -0.159928  0.778857 -0.729793 -2.213068  0.836170
3 -1.466165  0.939852 -0.276953  0.940895 -2.045292
4  0.109133  1.473001 -1.643116 -1.060425 -0.792009

In [40]:
# Drop rows
df_drop_rows = df_drop.drop([0, 1], axis=0)
df_drop_rows

          A         B         C         D         E         F         G
2 -0.159928 -1.413030  0.778857  0.044828 -0.729793 -2.213068  0.836170
3 -1.466165 -0.147145  0.939852  0.071958 -0.276953  0.940895 -2.045292
4  0.109133 -0.600886  1.473001  1.002607 -1.643116 -1.060425 -0.792009

### iterrows

- It allows to iterate through the rows of a DataFrame as Series objects.

In [41]:
df_iterrows = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_iterrows

          A         B         C
0  1.383489  0.600153  0.306984
1 -0.627833  0.829683  1.521263
2  1.519528 -0.263454  0.240439
3 -0.094221  1.744310  0.167192
4 -2.187793  0.597053 -0.007814

In [42]:
for index, row in df_iterrows.iterrows():
    print(f"Index: {index}")
    print(f"Row A value: {row['A']}")
    print(f"Row B value: {row['B']}")
    print(f"Row C value: {row['C']}")
    print("-----")

Index: 0
Row A value: 1.3834890719878756
Row B value: 0.6001530623066629
Row C value: 0.30698440773054847
-----
Index: 1
Row A value: -0.6278329169730842
Row B value: 0.8296832431095272
Row C value: 1.5212627525624882
-----
Index: 2
Row A value: 1.5195276149520733
Row B value: -0.2634541260655855
Row C value: 0.2404386380056439
-----
Index: 3
Row A value: -0.09422131313678603
Row B value: 1.7443096129087525
Row C value: 0.16719197773146968
-----
Index: 4
Row A value: -2.187792892954477
Row B value: 0.5970533490874543
Row C value: -0.007814080227349203
-----

### itertuples

- It will return an iterator yielding a namedtuple for each row in the DataFrame.

In [43]:
df_itertuple = pd.DataFrame(np.random.rand(3, 2), columns=["A", "B"])
df_itertuple

          A         B
0  0.494462  0.007959
1  0.407206  0.172206
2  0.855066  0.129621

In [44]:
for row in df_itertuple.itertuples():
    print(row)

Pandas(Index=0, A=0.49446172569216373, B=0.007958789940460842)
Pandas(Index=1, A=0.40720551073317934, B=0.1722058589613783)
Pandas(Index=2, A=0.8550655493152803, B=0.12962110412661731)

#### strftime

- It's a method used in programming (especially in Python) to convert a date/time into a nicely formatted string.

In [45]:
df_strftime = pd.Series(pd.period_range("20130101", periods=4))
df_strftime

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [46]:
df_strftime.dt.strftime('%Y-%m-%d')

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: object

In [47]:
df_strftime.dt.year

0    2013
1    2013
2    2013
3    2013
dtype: int64

In [48]:
df_strftime.dt.day

0    1
1    2
2    3
3    4
dtype: int64

## Sorting

In [49]:
s1 = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3], "c": [2, 3, 4]}).set_index(
    list("ab")
)
s1

     c
a b
B 1  2
a 2  3
C 3  4

In [50]:
s1.sort_index(level="a")

     c
a b
B 1  2
C 3  4
a 2  3

### Smallest and Largest

In [51]:
df_sm = pd.Series(np.random.permutation(10))
df_sm

0    2
1    5
2    8
3    9
4    1
5    3
6    6
7    0
8    7
9    4
dtype: int32

In [52]:
df_sm.nsmallest(3)

7    0
4    1
0    2
dtype: int32

In [53]:
df_sm.nlargest(3)

3    9
2    8
8    7
dtype: int32

### astype

In [54]:
df_astype = pd.DataFrame({
    "A": np.random.randint(1,15, size=4),
    "B": pd.Timestamp("20230102"),
    "C": pd.Series(range(4), dtype="float32"),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo",
})
df_astype

    A          B    C  D      E    F
0  12 2023-01-02  0.0  3   test  foo
1   3 2023-01-02  1.0  3  train  foo
2   7 2023-01-02  2.0  3   test  foo
3   1 2023-01-02  3.0  3  train  foo

In [55]:
df_astype.dtypes

A            int32
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [56]:
df_astype = df_astype.astype({"A": np.float64, "C": np.float64})
df_astype

      A          B    C  D      E    F
0  12.0 2023-01-02  0.0  3   test  foo
1   3.0 2023-01-02  1.0  3  train  foo
2   7.0 2023-01-02  2.0  3   test  foo
3   1.0 2023-01-02  3.0  3  train  foo

In [57]:
df_astype.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

### to_numeric

- It used to convert data into numeric values

In [59]:
df_numeric = pd.DataFrame({
    "A": ["1", 2, "3", 4],
    "B": [4.0, "5.5", "6.1", 7.2]
    })
df_numeric

   A    B
0  1  4.0
1  2  5.5
2  3  6.1
3  4  7.2

In [61]:
df_converted = df_numeric.astype({"A": "int32", "B": "float32"})
df_converted

   A    B
0  1  4.0
1  2  5.5
2  3  6.1
3  4  7.2