##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0    1.201410
1   -0.360579
2    1.375524
3    0.174056
4    0.229876
5   -0.493994
6    1.921628
7   -0.009048
8   -2.142708
9   -1.595276
dtype: float64

In [3]:
# Head
long_series.head()

0    1.201410
1   -0.360579
2    1.375524
3    0.174056
4    0.229876
dtype: float64

In [4]:
# Tail
long_series.tail()

5   -0.493994
6    1.921628
7   -0.009048
8   -2.142708
9   -1.595276
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.455934 -0.484435 -3.095705 -0.873960
2023-01-02 -0.094120 -0.828649  0.461120  1.384627
2023-01-03  0.509751  1.081533  0.285891 -0.114175
2023-01-04 -0.695153 -0.279017  2.552314  0.078188
2023-01-05 -0.855185 -0.611374  0.179522 -0.807489
2023-01-06 -0.195819 -1.229346 -0.857830 -0.650483
2023-01-07  0.310034  0.137489 -0.877490 -0.659725
2023-01-08  0.737271  0.198658  1.542553 -0.829532
2023-01-09  0.664542 -0.601449 -0.518036 -0.246955
2023-01-10  0.383585  0.852395  0.263991 -0.357218

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.455934 -0.484435 -3.095705 -0.873960
2023-01-02 -0.094120 -0.828649  0.461120  1.384627
2023-01-03  0.509751  1.081533  0.285891 -0.114175
2023-01-04 -0.695153 -0.279017  2.552314  0.078188
2023-01-05 -0.855185 -0.611374  0.179522 -0.807489
2023-01-06 -0.195819 -1.229346 -0.857830 -0.650483
2023-01-07  0.310034  0.137489 -0.877490 -0.659725
2023-01-08  0.737271  0.198658  1.542553 -0.829532
2023-01-09  0.664542 -0.601449 -0.518036 -0.246955
2023-01-10  0.383585  0.852395  0.263991 -0.357218

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[ 0.45593381, -0.48443472, -3.0957048 , -0.87395987],
       [-0.0941197 , -0.82864855,  0.46111998,  1.38462708],
       [ 0.509751  ,  1.08153346,  0.28589149, -0.11417517],
       [-0.69515314, -0.27901746,  2.55231372,  0.07818802],
       [-0.85518531, -0.61137401,  0.17952222, -0.80748858],
       [-0.19581863, -1.22934617, -0.85782981, -0.6504829 ],
       [ 0.31003381,  0.13748891, -0.87748954, -0.65972472],
       [ 0.73727055,  0.19865826,  1.54255293, -0.82953174],
       [ 0.66454168, -0.601449  , -0.5180359 , -0.24695452],
       [ 0.38358455,  0.85239451,  0.26399122, -0.35721782]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  2.0  1.0      7
b  9.0  8.0      6
c  7.0  8.0      5
d  NaN  NaN      4

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      7.0
two      8.0
three    5.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -5.0 -7.0    2.0
b  2.0  0.0    1.0
c  0.0  0.0    0.0
d  NaN  NaN   -1.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.455934 -0.484435 -3.095705 -0.873960
2023-01-02 -0.094120 -0.828649  0.461120  1.384627
2023-01-03  0.509751  1.081533       NaN -0.114175
2023-01-04 -0.695153 -0.279017  2.552314  0.078188
2023-01-05 -0.855185 -0.611374  0.179522 -0.807489

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.455934 -0.484435 -3.095705 -0.873960
2023-01-02 -0.094120 -0.828649  0.461120  1.384627
2023-01-03  0.509751  1.081533       NaN -0.114175
2023-01-04 -0.695153 -0.279017  2.552314  0.078188
2023-01-05 -0.855185 -0.611374  0.179522 -0.807489

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0 -1.278284  0.648555  0.233397
1 -1.519891  0.169426 -1.202190
2 -0.395130 -1.886740  1.159239
3 -0.343714 -0.334341  0.235089
4 -0.240167 -0.025939  1.684924

In [17]:
df_max_min.idxmax(axis=0)

A    4
B    0
C    4
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    A
1    A
2    B
3    A
4    A
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([6, 1, 3, 1, 2, 2, 2, 0, 2, 0, 4, 6, 1, 1, 1, 6, 4, 5, 5, 5, 4, 4,
       2, 3, 6, 5, 3, 4, 6, 2, 3, 4, 5, 6, 4, 2, 5, 4, 0, 2, 1, 4, 1, 2,
       3, 4, 0, 0, 1, 0])

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

4    10
2     9
1     8
6     6
0     6
5     6
3     5
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  2  2  0
1  3  0  0
2  2  3  4
3  2  0  1

In [28]:
df_apply.apply(np.sum, axis=0)

A    9
B    5
C    5
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    9    3    2
B    5    3    0
C    5    4    0

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [30]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  4  6  4
2000-01-02  9  9  8
2000-01-03  4  4  8
2000-01-04  4  4  5
2000-01-05  8  7  3
2000-01-06  6  5  5
2000-01-07  6  3  3
2000-01-08  9  6  6
2000-01-09  8  4  3
2000-01-10  3  8  9

In [31]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  2.000000  5  16
2000-01-02  3.000000  8  64
2000-01-03  2.000000  3  64
2000-01-04  2.000000  3  25
2000-01-05  2.828427  6   9
2000-01-06  2.449490  4  25
2000-01-07  2.449490  2   9
2000-01-08  3.000000  5  36
2000-01-09  2.828427  3   9
2000-01-10  1.732051  7  81

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [40]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a   -0.726619
b    0.677710
c   -1.334372
d    0.096897
e    1.284663
dtype: float64

In [42]:
s.reindex(["e", "d", "a"])

e    1.284663
d    0.096897
a   -0.726619
dtype: float64