##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0    0.598589
1    0.851980
2    1.399567
3   -0.398633
4    0.962491
5   -0.240440
6    0.476138
7   -1.143615
8   -0.147626
9    0.574270
dtype: float64

In [3]:
# Head
long_series.head()

0    0.598589
1    0.851980
2    1.399567
3   -0.398633
4    0.962491
dtype: float64

In [4]:
# Tail
long_series.tail()

5   -0.240440
6    0.476138
7   -1.143615
8   -0.147626
9    0.574270
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.825410  1.025219  1.986470  1.922798
2023-01-02  0.722691  1.032119 -0.260901  0.504604
2023-01-03  0.188613 -0.143509  1.989271 -1.547829
2023-01-04 -0.367817 -1.671597 -0.889354 -0.760720
2023-01-05 -0.616917  0.869575 -0.782202 -0.553906
2023-01-06 -0.505970 -0.762735 -0.570627  0.106715
2023-01-07 -1.521969  1.582063 -1.079858  0.742190
2023-01-08  0.195242 -1.183747 -0.442739  0.317272
2023-01-09  0.561285 -1.262656 -0.280729  0.496329
2023-01-10 -1.229956 -0.688282  0.141872 -1.249303

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.825410  1.025219  1.986470  1.922798
2023-01-02  0.722691  1.032119 -0.260901  0.504604
2023-01-03  0.188613 -0.143509  1.989271 -1.547829
2023-01-04 -0.367817 -1.671597 -0.889354 -0.760720
2023-01-05 -0.616917  0.869575 -0.782202 -0.553906
2023-01-06 -0.505970 -0.762735 -0.570627  0.106715
2023-01-07 -1.521969  1.582063 -1.079858  0.742190
2023-01-08  0.195242 -1.183747 -0.442739  0.317272
2023-01-09  0.561285 -1.262656 -0.280729  0.496329
2023-01-10 -1.229956 -0.688282  0.141872 -1.249303

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[ 0.82540996,  1.02521921,  1.98647023,  1.9227984 ],
       [ 0.72269081,  1.03211917, -0.26090109,  0.50460399],
       [ 0.18861327, -0.14350902,  1.98927143, -1.54782924],
       [-0.36781683, -1.67159735, -0.88935413, -0.7607197 ],
       [-0.61691735,  0.86957518, -0.78220197, -0.55390575],
       [-0.5059698 , -0.76273507, -0.57062704,  0.1067153 ],
       [-1.5219685 ,  1.58206269, -1.07985764,  0.74218999],
       [ 0.19524157, -1.18374665, -0.44273879,  0.31727231],
       [ 0.56128539, -1.26265605, -0.28072868,  0.49632947],
       [-1.22995647, -0.68828201,  0.14187228, -1.24930323]])

## Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  7.0  2.0      8
b  8.0  1.0      9
c  8.0  1.0      8
d  NaN  NaN      8

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      8.0
two      1.0
three    8.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -1.0  1.0    0.0
b  0.0  0.0    1.0
c  0.0  0.0    0.0
d  NaN  NaN    0.0

## Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.825410  1.025219  1.986470  1.922798
2023-01-02  0.722691  1.032119 -0.260901  0.504604
2023-01-03  0.188613 -0.143509       NaN -1.547829
2023-01-04 -0.367817 -1.671597 -0.889354 -0.760720
2023-01-05 -0.616917  0.869575 -0.782202 -0.553906

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.825410  1.025219  1.986470  1.922798
2023-01-02  0.722691  1.032119 -0.260901  0.504604
2023-01-03  0.188613 -0.143509       NaN -1.547829
2023-01-04 -0.367817 -1.671597 -0.889354 -0.760720
2023-01-05 -0.616917  0.869575 -0.782202 -0.553906

## Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0 -0.466864  0.237666 -1.980267
1  1.562207  0.087789  0.164337
2 -0.718001 -0.291431 -0.051480
3  2.282155 -0.785059 -0.276585
4 -0.485989 -1.704000 -0.561943

In [17]:
df_max_min.idxmax(axis=0)

A    3
B    0
C    1
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    C
1    B
2    A
3    B
4    B
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([6, 6, 5, 0, 5, 6, 6, 1, 1, 0, 0, 3, 2, 2, 6, 5, 3, 0, 5, 4, 6, 0,
       3, 0, 1, 6, 6, 1, 2, 0, 6, 4, 0, 4, 3, 5, 4, 6, 3, 5, 6, 3, 1, 2,
       1, 5, 3, 0, 4, 4], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

6    11
0     9
5     7
3     7
1     6
4     6
2     4
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [39]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  3  1  4
1  4  0  1
2  3  1  0
3  3  0  1

In [40]:
df_apply.apply(np.sum, axis=0)

A    13
B     2
C     6
dtype: int64