##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -0.641987
1    0.898312
2    0.795735
3   -0.001472
4   -0.643478
5    0.524105
6   -0.671694
7   -1.029817
8   -0.455181
9   -0.569913
dtype: float64

In [3]:
# Head
long_series.head()

0   -0.641987
1    0.898312
2    0.795735
3   -0.001472
4   -0.643478
dtype: float64

In [4]:
# Tail
long_series.tail()

5    0.524105
6   -0.671694
7   -1.029817
8   -0.455181
9   -0.569913
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01 -0.153677 -0.267777 -0.956755  0.872136
2023-01-02  0.147341 -1.922432 -1.294956 -0.635983
2023-01-03 -1.056962  1.171437  0.907299  0.306623
2023-01-04 -1.089844  0.570180 -0.507305  0.894793
2023-01-05 -1.310714 -0.118990  0.732921  0.168930
2023-01-06  1.137405 -1.410589  1.389108  0.671408
2023-01-07  1.042363  0.594253 -0.509344  1.212018
2023-01-08 -1.641269 -1.136359  0.558599  0.371675
2023-01-09 -0.645370  1.839923  0.356095  0.012908
2023-01-10  0.594504  0.966956 -0.475101  0.330303

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01 -0.153677 -0.267777 -0.956755  0.872136
2023-01-02  0.147341 -1.922432 -1.294956 -0.635983
2023-01-03 -1.056962  1.171437  0.907299  0.306623
2023-01-04 -1.089844  0.570180 -0.507305  0.894793
2023-01-05 -1.310714 -0.118990  0.732921  0.168930
2023-01-06  1.137405 -1.410589  1.389108  0.671408
2023-01-07  1.042363  0.594253 -0.509344  1.212018
2023-01-08 -1.641269 -1.136359  0.558599  0.371675
2023-01-09 -0.645370  1.839923  0.356095  0.012908
2023-01-10  0.594504  0.966956 -0.475101  0.330303

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[-0.15367681, -0.26777659, -0.95675451,  0.87213577],
       [ 0.14734079, -1.92243223, -1.29495607, -0.6359829 ],
       [-1.05696157,  1.17143689,  0.90729891,  0.30662334],
       [-1.08984377,  0.57018024, -0.50730512,  0.8947935 ],
       [-1.31071381, -0.11899004,  0.73292106,  0.16892998],
       [ 1.13740488, -1.41058884,  1.3891082 ,  0.67140835],
       [ 1.04236317,  0.59425292, -0.5093437 ,  1.21201777],
       [-1.64126946, -1.13635899,  0.55859894,  0.37167527],
       [-0.64536959,  1.83992329,  0.35609469,  0.01290829],
       [ 0.59450389,  0.96695642, -0.47510069,  0.33030282]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  2.0  9.0      6
b  4.0  7.0      9
c  4.0  7.0      9
d  NaN  NaN      3

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      4.0
two      7.0
three    9.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -2.0  2.0   -3.0
b  0.0  0.0    0.0
c  0.0  0.0    0.0
d  NaN  NaN   -6.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01 -0.153677 -0.267777 -0.956755  0.872136
2023-01-02  0.147341 -1.922432 -1.294956 -0.635983
2023-01-03 -1.056962  1.171437       NaN  0.306623
2023-01-04 -1.089844  0.570180 -0.507305  0.894793
2023-01-05 -1.310714 -0.118990  0.732921  0.168930

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01 -0.153677 -0.267777 -0.956755  0.872136
2023-01-02  0.147341 -1.922432 -1.294956 -0.635983
2023-01-03 -1.056962  1.171437       NaN  0.306623
2023-01-04 -1.089844  0.570180 -0.507305  0.894793
2023-01-05 -1.310714 -0.118990  0.732921  0.168930

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0  1.040856 -0.347423  0.397352
1  1.448277 -0.769908 -0.467077
2 -0.335367  0.124322 -1.785441
3  1.907233 -0.441189  0.748344
4  2.405822  0.152864  0.330125

In [17]:
df_max_min.idxmax(axis=0)

A    4
B    4
C    3
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    B
1    B
2    C
3    B
4    B
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([6, 3, 2, 3, 1, 1, 3, 3, 2, 4, 4, 3, 3, 3, 0, 5, 4, 3, 4, 4, 0, 3,
       0, 5, 1, 4, 1, 1, 3, 2, 6, 2, 3, 0, 3, 0, 5, 4, 6, 6, 6, 6, 0, 0,
       0, 6, 0, 0, 3, 2], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

3    13
0    10
6     7
4     7
2     5
1     5
5     3
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  3  4  0
1  4  2  1
2  4  4  4
3  0  1  3

In [28]:
df_apply.apply(np.sum, axis=0)

A    11
B    11
C     8
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A   11    4    0
B   11    4    1
C    8    4    0

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [30]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  7  6  5
2000-01-02  4  8  8
2000-01-03  8  9  9
2000-01-04  7  5  8
2000-01-05  6  6  6
2000-01-06  9  7  5
2000-01-07  8  5  5
2000-01-08  3  8  5
2000-01-09  4  8  9
2000-01-10  7  6  5

In [31]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  2.645751  5  25
2000-01-02  2.000000  7  64
2000-01-03  2.828427  8  81
2000-01-04  2.645751  4  64
2000-01-05  2.449490  5  36
2000-01-06  3.000000  6  25
2000-01-07  2.828427  4  25
2000-01-08  1.732051  7  25
2000-01-09  2.000000  7  81
2000-01-10  2.645751  5  25

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [32]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a    0.163541
b   -0.476056
c    0.189211
d   -0.518508
e    0.525596
dtype: float64

In [33]:
s.reindex(["e", "d", "a"])

e    0.525596
d   -0.518508
a    0.163541
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [47]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [48]:
ts

2000-01-03   -0.225869
2000-01-04   -0.645639
2000-01-05    0.735959
2000-01-06    1.626807
2000-01-07    0.574159
2000-01-08   -0.696855
2000-01-09   -2.071452
2000-01-10   -0.689787
Freq: D, dtype: float64

In [49]:
ts2.reindex(ts.index)

2000-01-03   -0.225869
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    1.626807
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -2.071452
2000-01-10         NaN
Freq: D, dtype: float64

In [53]:
ts2.reindex(rng, method="nearest")

2000-01-03   -0.225869
2000-01-04   -0.225869
2000-01-05    1.626807
2000-01-06    1.626807
2000-01-07    1.626807
2000-01-08   -2.071452
2000-01-09   -2.071452
2000-01-10   -2.071452
Freq: D, dtype: float64