##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -0.178987
1   -0.464044
2    0.971165
3    0.837708
4    2.250428
5    0.153377
6   -0.712398
7    1.527972
8    2.128089
9   -1.132036
dtype: float64

In [3]:
# Head
long_series.head()

0   -0.178987
1   -0.464044
2    0.971165
3    0.837708
4    2.250428
dtype: float64

In [4]:
# Tail
long_series.tail()

5    0.153377
6   -0.712398
7    1.527972
8    2.128089
9   -1.132036
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01 -0.360971 -0.101602 -0.592203 -0.231673
2023-01-02  0.682547 -1.291068 -0.230666 -1.222428
2023-01-03 -0.345703  0.342102 -0.521463 -0.392716
2023-01-04 -0.561726  1.633826  0.596185 -0.048575
2023-01-05 -0.396065 -1.885107  0.661412  0.730854
2023-01-06  0.910784  1.462823  0.499634 -1.954081
2023-01-07 -0.289604  0.605113 -1.122599  0.900964
2023-01-08  0.595455  0.575360 -0.779536 -1.777530
2023-01-09 -1.652063 -0.196649 -0.527385  0.923599
2023-01-10 -0.294185  0.964282  0.096100 -0.385665

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01 -0.360971 -0.101602 -0.592203 -0.231673
2023-01-02  0.682547 -1.291068 -0.230666 -1.222428
2023-01-03 -0.345703  0.342102 -0.521463 -0.392716
2023-01-04 -0.561726  1.633826  0.596185 -0.048575
2023-01-05 -0.396065 -1.885107  0.661412  0.730854
2023-01-06  0.910784  1.462823  0.499634 -1.954081
2023-01-07 -0.289604  0.605113 -1.122599  0.900964
2023-01-08  0.595455  0.575360 -0.779536 -1.777530
2023-01-09 -1.652063 -0.196649 -0.527385  0.923599
2023-01-10 -0.294185  0.964282  0.096100 -0.385665

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[-0.36097052, -0.10160214, -0.59220262, -0.23167269],
       [ 0.68254678, -1.29106834, -0.23066607, -1.22242783],
       [-0.3457034 ,  0.34210212, -0.52146314, -0.39271587],
       [-0.56172585,  1.63382634,  0.59618505, -0.04857457],
       [-0.39606451, -1.88510711,  0.66141222,  0.73085401],
       [ 0.91078438,  1.46282337,  0.49963366, -1.95408099],
       [-0.28960403,  0.60511331, -1.12259876,  0.90096382],
       [ 0.59545457,  0.5753604 , -0.77953618, -1.77752963],
       [-1.6520632 , -0.19664864, -0.52738539,  0.92359879],
       [-0.29418532,  0.96428209,  0.09610015, -0.38566535]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  7.0  9.0      1
b  6.0  5.0      7
c  0.0  0.0      0
d  NaN  NaN      5

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      0.0
two      0.0
three    0.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a  7.0  9.0    1.0
b  6.0  5.0    7.0
c  0.0  0.0    0.0
d  NaN  NaN    5.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01 -0.360971 -0.101602 -0.592203 -0.231673
2023-01-02  0.682547 -1.291068 -0.230666 -1.222428
2023-01-03 -0.345703  0.342102       NaN -0.392716
2023-01-04 -0.561726  1.633826  0.596185 -0.048575
2023-01-05 -0.396065 -1.885107  0.661412  0.730854

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01 -0.360971 -0.101602 -0.592203 -0.231673
2023-01-02  0.682547 -1.291068 -0.230666 -1.222428
2023-01-03 -0.345703  0.342102       NaN -0.392716
2023-01-04 -0.561726  1.633826  0.596185 -0.048575
2023-01-05 -0.396065 -1.885107  0.661412  0.730854

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0  0.307602  1.141166 -1.124457
1  0.277386 -0.775057 -1.123712
2 -0.722336  0.068284  0.326139
3  0.703892  1.998447 -1.027059
4 -1.350149  0.888943  0.659238

In [17]:
df_max_min.idxmax(axis=0)

A    3
B    3
C    4
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    C
1    C
2    A
3    C
4    A
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([3, 2, 6, 6, 5, 4, 2, 5, 5, 0, 1, 1, 3, 1, 6, 3, 0, 2, 1, 0, 2, 4,
       2, 4, 1, 2, 5, 3, 3, 4, 4, 4, 1, 3, 4, 5, 2, 5, 2, 2, 3, 3, 4, 3,
       6, 6, 2, 1, 3, 5])

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

3    10
2    10
4     8
5     7
1     7
6     5
0     3
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  2  4  4
1  0  1  1
2  3  1  2
3  1  0  4

In [28]:
df_apply.apply(np.sum, axis=0)

A     6
B     6
C    11
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    6    3    0
B    6    4    0
C   11    4    1

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [58]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  3  9  5
2000-01-02  8  5  9
2000-01-03  6  5  6
2000-01-04  6  9  4
2000-01-05  5  7  4
2000-01-06  4  6  4
2000-01-07  9  6  5
2000-01-08  3  8  8
2000-01-09  8  5  6
2000-01-10  5  3  4

In [64]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  1.732051  8  25
2000-01-02  2.828427  4  81
2000-01-03  2.449490  4  36
2000-01-04  2.449490  8  16
2000-01-05  2.236068  6  16
2000-01-06  2.000000  5  16
2000-01-07  3.000000  5  25
2000-01-08  1.732051  7  64
2000-01-09  2.828427  4  36
2000-01-10  2.236068  2  16