##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -0.940370
1   -0.928936
2    1.005797
3   -0.026185
4   -1.884886
5    1.308513
6   -1.380159
7    0.317539
8    0.376567
9   -0.801729
dtype: float64

In [3]:
# Head
long_series.head()

0   -0.940370
1   -0.928936
2    1.005797
3   -0.026185
4   -1.884886
dtype: float64

In [4]:
# Tail
long_series.tail()

5    1.308513
6   -1.380159
7    0.317539
8    0.376567
9   -0.801729
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.541607  0.563693  0.618944  0.278450
2023-01-02 -0.194787  0.189839 -0.852505  1.705395
2023-01-03  0.964799 -1.451923  0.105369 -0.111852
2023-01-04 -0.913330 -0.335636 -0.115527  0.858604
2023-01-05  1.931287  0.886856 -0.722425  0.781069
2023-01-06  0.690290 -1.158726 -0.290523  0.143144
2023-01-07 -0.323742 -1.384799  0.392179 -0.732682
2023-01-08  0.783320  0.266961  0.737082  0.594143
2023-01-09  0.714962 -0.547014  0.283960 -1.251390
2023-01-10  0.069081 -0.059663 -0.442339  1.454044

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.541607  0.563693  0.618944  0.278450
2023-01-02 -0.194787  0.189839 -0.852505  1.705395
2023-01-03  0.964799 -1.451923  0.105369 -0.111852
2023-01-04 -0.913330 -0.335636 -0.115527  0.858604
2023-01-05  1.931287  0.886856 -0.722425  0.781069
2023-01-06  0.690290 -1.158726 -0.290523  0.143144
2023-01-07 -0.323742 -1.384799  0.392179 -0.732682
2023-01-08  0.783320  0.266961  0.737082  0.594143
2023-01-09  0.714962 -0.547014  0.283960 -1.251390
2023-01-10  0.069081 -0.059663 -0.442339  1.454044

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[ 0.54160699,  0.56369346,  0.61894375,  0.27845049],
       [-0.19478658,  0.1898391 , -0.85250513,  1.7053949 ],
       [ 0.96479857, -1.45192323,  0.10536852, -0.11185157],
       [-0.91332991, -0.33563633, -0.11552712,  0.858604  ],
       [ 1.93128663,  0.88685611, -0.72242505,  0.78106927],
       [ 0.69029005, -1.15872568, -0.29052337,  0.14314446],
       [-0.3237425 , -1.3847994 ,  0.39217917, -0.73268226],
       [ 0.78332017,  0.26696054,  0.73708193,  0.59414315],
       [ 0.71496202, -0.54701427,  0.28396034, -1.25138976],
       [ 0.0690811 , -0.05966275, -0.44233902,  1.45404415]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  3.0  6.0      8
b  1.0  3.0      8
c  6.0  0.0      7
d  NaN  NaN      3

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      6.0
two      0.0
three    7.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -3.0  6.0    1.0
b -5.0  3.0    1.0
c  0.0  0.0    0.0
d  NaN  NaN   -4.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.541607  0.563693  0.618944  0.278450
2023-01-02 -0.194787  0.189839 -0.852505  1.705395
2023-01-03  0.964799 -1.451923       NaN -0.111852
2023-01-04 -0.913330 -0.335636 -0.115527  0.858604
2023-01-05  1.931287  0.886856 -0.722425  0.781069

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.541607  0.563693  0.618944  0.278450
2023-01-02 -0.194787  0.189839 -0.852505  1.705395
2023-01-03  0.964799 -1.451923       NaN -0.111852
2023-01-04 -0.913330 -0.335636 -0.115527  0.858604
2023-01-05  1.931287  0.886856 -0.722425  0.781069

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0 -0.734889 -0.461116  0.955819
1 -0.733645 -0.764304 -0.419563
2 -0.405340 -0.994160 -0.694145
3 -2.808442 -1.233134  0.648679
4  1.156124  0.445498  1.803995

In [17]:
df_max_min.idxmax(axis=0)

A    4
B    4
C    4
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    A
1    B
2    B
3    A
4    B
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([6, 1, 5, 3, 4, 3, 6, 2, 1, 6, 0, 5, 0, 4, 2, 5, 4, 6, 6, 6, 5, 2,
       0, 0, 3, 4, 3, 5, 3, 1, 3, 1, 0, 2, 1, 4, 5, 2, 3, 2, 3, 6, 5, 0,
       6, 0, 3, 3, 0, 5], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

3    10
5     8
6     8
0     8
2     6
1     5
4     5
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  3  4  3
1  0  4  4
2  0  3  2
3  4  0  2

In [28]:
df_apply.apply(np.sum, axis=0)

A     7
B    11
C    11
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    7    4    0
B   11    4    0
C   11    4    2

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [30]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  4  5  8
2000-01-02  7  4  8
2000-01-03  8  7  8
2000-01-04  4  5  5
2000-01-05  5  9  4
2000-01-06  6  3  7
2000-01-07  7  9  5
2000-01-08  7  6  8
2000-01-09  7  3  7
2000-01-10  7  7  3

In [31]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  2.000000  4  64
2000-01-02  2.645751  3  64
2000-01-03  2.828427  6  64
2000-01-04  2.000000  4  25
2000-01-05  2.236068  8  16
2000-01-06  2.449490  2  49
2000-01-07  2.645751  8  25
2000-01-08  2.645751  5  64
2000-01-09  2.645751  2  49
2000-01-10  2.645751  6   9

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [32]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a   -1.328482
b    1.653520
c    0.569041
d    1.751370
e    0.642246
dtype: float64

In [33]:
s.reindex(["e", "d", "a"])

e    0.642246
d    1.751370
a   -1.328482
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [34]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [35]:
ts

2000-01-03   -0.983523
2000-01-04    0.315081
2000-01-05    0.175678
2000-01-06   -0.400958
2000-01-07    2.315633
2000-01-08   -0.655664
2000-01-09    0.836196
2000-01-10    1.061769
Freq: D, dtype: float64

In [36]:
ts2.reindex(ts.index)

2000-01-03   -0.983523
2000-01-04         NaN
2000-01-05         NaN
2000-01-06   -0.400958
2000-01-07         NaN
2000-01-08         NaN
2000-01-09    0.836196
2000-01-10         NaN
Freq: D, dtype: float64

In [37]:
ts2.reindex(rng, method="nearest")

2000-01-03   -0.983523
2000-01-04   -0.983523
2000-01-05   -0.400958
2000-01-06   -0.400958
2000-01-07   -0.400958
2000-01-08    0.836196
2000-01-09    0.836196
2000-01-10    0.836196
Freq: D, dtype: float64

### Dropping Labels from an axis

In [38]:
df_drop = pd.DataFrame(np.random.randn(5, 7), columns=["A", "B", "C", "D", "E", "F", "G"])
df_drop

          A         B         C         D         E         F         G
0  0.729838  0.712876 -0.382484  1.845264  1.302546 -0.622314 -0.764064
1  1.457056 -0.321897  0.854403  0.910976 -0.856977 -1.268547 -0.442645
2 -0.383600 -0.909814 -0.153932 -0.813339  0.790990 -0.356090  0.914907
3  0.436423  0.033687 -1.054337  0.642656  1.500480 -1.052540 -0.748002
4 -0.766184 -0.661601 -0.010479 -0.460467 -0.691550 -0.723405  0.404252

In [39]:
# Drop columns
df_drop_columns = df_drop.drop(["B", "D"], axis=1)
df_drop_columns

          A         C         E         F         G
0  0.729838 -0.382484  1.302546 -0.622314 -0.764064
1  1.457056  0.854403 -0.856977 -1.268547 -0.442645
2 -0.383600 -0.153932  0.790990 -0.356090  0.914907
3  0.436423 -1.054337  1.500480 -1.052540 -0.748002
4 -0.766184 -0.010479 -0.691550 -0.723405  0.404252

In [40]:
# Drop rows
df_drop_rows = df_drop.drop([0, 1], axis=0)
df_drop_rows

          A         B         C         D        E         F         G
2 -0.383600 -0.909814 -0.153932 -0.813339  0.79099 -0.356090  0.914907
3  0.436423  0.033687 -1.054337  0.642656  1.50048 -1.052540 -0.748002
4 -0.766184 -0.661601 -0.010479 -0.460467 -0.69155 -0.723405  0.404252

### iterrows

- It allows to iterate through the rows of a DataFrame as Series objects.

In [41]:
df_iterrows = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_iterrows

          A         B         C
0 -0.131274  0.381376 -0.762422
1  0.888815 -0.334886 -0.452218
2  0.096401 -0.538899 -1.557896
3  0.502410  0.820309  0.326829
4 -0.535452  2.047764  1.467157

In [42]:
for index, row in df_iterrows.iterrows():
    print(f"Index: {index}")
    print(f"Row A value: {row['A']}")
    print(f"Row B value: {row['B']}")
    print(f"Row C value: {row['C']}")
    print("-----")

Index: 0
Row A value: -0.1312742124925541
Row B value: 0.3813760914204161
Row C value: -0.762421689974862
-----
Index: 1
Row A value: 0.8888153207306877
Row B value: -0.3348863913382397
Row C value: -0.45221756668765495
-----
Index: 2
Row A value: 0.09640104777200313
Row B value: -0.5388988509691098
Row C value: -1.5578963066469798
-----
Index: 3
Row A value: 0.5024097712924465
Row B value: 0.8203093871065866
Row C value: 0.3268286895207566
-----
Index: 4
Row A value: -0.5354521555253502
Row B value: 2.047763857646774
Row C value: 1.46715697590566
-----

### itertuples

- It will return an iterator yielding a namedtuple for each row in the DataFrame.

In [43]:
df_itertuple = pd.DataFrame(np.random.rand(3, 2), columns=["A", "B"])
df_itertuple

          A         B
0  0.433566  0.175085
1  0.655702  0.468917
2  0.323054  0.363743

In [44]:
for row in df_itertuple.itertuples():
    print(row)

Pandas(Index=0, A=0.4335661667448416, B=0.1750851208442905)
Pandas(Index=1, A=0.6557019457547055, B=0.4689167786381858)
Pandas(Index=2, A=0.32305387175959943, B=0.3637426569007336)

#### strftime

- It's a method used in programming (especially in Python) to convert a date/time into a nicely formatted string.

In [45]:
df_strftime = pd.Series(pd.period_range("20130101", periods=4))
df_strftime

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [46]:
df_strftime.dt.strftime('%Y-%m-%d')

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: object

In [47]:
df_strftime.dt.year

0    2013
1    2013
2    2013
3    2013
dtype: int64

In [48]:
df_strftime.dt.day

0    1
1    2
2    3
3    4
dtype: int64

## Sorting

In [49]:
s1 = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3], "c": [2, 3, 4]}).set_index(
    list("ab")
)
s1

     c
a b
B 1  2
a 2  3
C 3  4

In [50]:
s1.sort_index(level="a")

     c
a b
B 1  2
C 3  4
a 2  3

### Smallest and Largest

In [51]:
df_sm = pd.Series(np.random.permutation(10))
df_sm

0    1
1    2
2    6
3    7
4    4
5    9
6    0
7    8
8    5
9    3
dtype: int32

In [52]:
df_sm.nsmallest(3)

6    0
0    1
1    2
dtype: int32

In [54]:
df_sm.nlargest(3)

5    9
7    8
3    7
dtype: int32