##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -1.937462
1   -1.580668
2   -0.279397
3   -1.932504
4   -0.813173
5   -1.714331
6    0.469271
7    0.104141
8   -0.582830
9   -0.767536
dtype: float64

In [3]:
# Head
long_series.head()

0   -1.937462
1   -1.580668
2   -0.279397
3   -1.932504
4   -0.813173
dtype: float64

In [4]:
# Tail
long_series.tail()

5   -1.714331
6    0.469271
7    0.104141
8   -0.582830
9   -0.767536
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.218160 -0.862328 -0.325037  0.336805
2023-01-02 -0.905054  0.635386 -0.598455  1.151474
2023-01-03  0.295804  1.159272 -0.095849  0.278266
2023-01-04  0.718330 -0.750393  0.508913  0.825978
2023-01-05 -1.441317 -0.804346 -0.640063 -0.765746
2023-01-06  1.020943 -0.407072  0.232404  0.148773
2023-01-07 -1.860892 -0.736048  0.189761 -0.805603
2023-01-08  1.058139 -0.172371  0.585765  0.500240
2023-01-09 -0.879600  0.677431  0.071534 -0.099123
2023-01-10  1.451805  0.669835  0.359588 -0.924757

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.218160 -0.862328 -0.325037  0.336805
2023-01-02 -0.905054  0.635386 -0.598455  1.151474
2023-01-03  0.295804  1.159272 -0.095849  0.278266
2023-01-04  0.718330 -0.750393  0.508913  0.825978
2023-01-05 -1.441317 -0.804346 -0.640063 -0.765746
2023-01-06  1.020943 -0.407072  0.232404  0.148773
2023-01-07 -1.860892 -0.736048  0.189761 -0.805603
2023-01-08  1.058139 -0.172371  0.585765  0.500240
2023-01-09 -0.879600  0.677431  0.071534 -0.099123
2023-01-10  1.451805  0.669835  0.359588 -0.924757

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[ 0.21816028, -0.86232759, -0.32503692,  0.33680549],
       [-0.90505373,  0.6353863 , -0.59845501,  1.15147385],
       [ 0.29580419,  1.15927219, -0.09584903,  0.27826588],
       [ 0.71833036, -0.75039312,  0.50891313,  0.82597808],
       [-1.44131733, -0.80434591, -0.64006288, -0.76574602],
       [ 1.0209427 , -0.40707223,  0.23240431,  0.14877343],
       [-1.86089248, -0.73604792,  0.18976102, -0.80560311],
       [ 1.05813888, -0.17237063,  0.58576476,  0.50023965],
       [-0.87960019,  0.67743092,  0.07153373, -0.09912345],
       [ 1.45180462,  0.66983459,  0.35958802, -0.92475704]])

## Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  8.0  0.0      2
b  8.0  2.0      5
c  4.0  6.0      7
d  NaN  NaN      8

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      4.0
two      6.0
three    7.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a  4.0 -6.0   -5.0
b  4.0 -4.0   -2.0
c  0.0  0.0    0.0
d  NaN  NaN    1.0

## Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.235744  1.169579 -0.277432  0.196306
2023-01-02  1.488578  1.612231  0.423731 -0.243339
2023-01-03  0.718891  1.571629       NaN  0.422503
2023-01-04 -0.709481 -0.805459 -1.672329  0.840812
2023-01-05  0.212755  0.343646  2.025267 -0.382744

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.235744  1.169579 -0.277432  0.196306
2023-01-02  1.488578  1.612231  0.423731 -0.243339
2023-01-03  0.718891  1.571629       NaN  0.422503
2023-01-04 -0.709481 -0.805459 -1.672329  0.840812
2023-01-05  0.212755  0.343646  2.025267 -0.382744

## Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0 -0.393045 -0.414970  1.121571
1 -0.778476  0.472549  0.542938
2  0.371143 -1.180934 -0.403236
3  0.707002 -0.772121 -0.296454
4 -0.846420  1.127337  0.940540

In [17]:
df_max_min.idxmax(axis=0)

A    3
B    4
C    0
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    B
1    A
2    B
3    B
4    A
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([3, 2, 3, 5, 0, 2, 2, 1, 1, 0, 1, 4, 0, 2, 5, 3, 0, 6, 5, 0, 0, 4,
       3, 2, 3, 1, 4, 3, 4, 0, 5, 1, 3, 0, 0, 6, 1, 3, 1, 3, 6, 3, 1, 1,
       6, 6, 3, 0, 2, 3])

In [21]:
s = pd.Series(data_hist_value)

In [22]:
s.value_counts()

3    12
0    10
1     9
2     6
6     5
5     4
4     4
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [13]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [ ]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [ ]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [ ]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [ ]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q5']
Categories (5, object): ['Q1' < 'Q2' < 'Q3' < 'Q4' < 'Q5']