##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -1.333875
1   -1.417069
2   -0.185768
3    0.907343
4   -1.748456
5    0.078312
6    2.067915
7   -0.717282
8   -1.120462
9    0.335193
dtype: float64

In [3]:
# Head
long_series.head()

0   -1.333875
1   -1.417069
2   -0.185768
3    0.907343
4   -1.748456
dtype: float64

In [4]:
# Tail
long_series.tail()

5    0.078312
6    2.067915
7   -0.717282
8   -1.120462
9    0.335193
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.419660 -0.834225  0.064101 -0.678894
2023-01-02  0.735682 -0.378234  1.069263  0.267694
2023-01-03 -0.403999  0.496314 -0.995325  1.585226
2023-01-04 -0.725328  1.423956 -0.669006  0.128995
2023-01-05  0.891227 -0.083633 -1.769143  0.243666
2023-01-06 -0.668960  1.884857 -0.299351  0.806835
2023-01-07 -0.586000 -1.435472 -0.656164  0.484606
2023-01-08  0.886599  1.506782 -0.953342 -0.615978
2023-01-09  0.996197  0.724250 -0.302529  0.195199
2023-01-10 -1.980210  0.223266 -0.963859 -1.316811

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.419660 -0.834225  0.064101 -0.678894
2023-01-02  0.735682 -0.378234  1.069263  0.267694
2023-01-03 -0.403999  0.496314 -0.995325  1.585226
2023-01-04 -0.725328  1.423956 -0.669006  0.128995
2023-01-05  0.891227 -0.083633 -1.769143  0.243666
2023-01-06 -0.668960  1.884857 -0.299351  0.806835
2023-01-07 -0.586000 -1.435472 -0.656164  0.484606
2023-01-08  0.886599  1.506782 -0.953342 -0.615978
2023-01-09  0.996197  0.724250 -0.302529  0.195199
2023-01-10 -1.980210  0.223266 -0.963859 -1.316811

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[ 0.41966013, -0.8342251 ,  0.06410079, -0.67889427],
       [ 0.73568212, -0.37823447,  1.06926304,  0.26769399],
       [-0.40399905,  0.49631352, -0.99532458,  1.58522572],
       [-0.72532785,  1.42395625, -0.66900627,  0.12899478],
       [ 0.89122661, -0.08363341, -1.7691426 ,  0.24366555],
       [-0.66895998,  1.88485674, -0.29935056,  0.80683459],
       [-0.58600036, -1.43547157, -0.65616358,  0.48460604],
       [ 0.88659851,  1.50678164, -0.95334234, -0.61597819],
       [ 0.9961967 ,  0.72425017, -0.30252856,  0.19519933],
       [-1.9802098 ,  0.22326631, -0.96385865, -1.31681094]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  0.0  7.0      7
b  4.0  4.0      1
c  8.0  4.0      2
d  NaN  NaN      9

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      8.0
two      4.0
three    2.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -8.0  3.0    5.0
b -4.0  0.0   -1.0
c  0.0  0.0    0.0
d  NaN  NaN    7.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.419660 -0.834225  0.064101 -0.678894
2023-01-02  0.735682 -0.378234  1.069263  0.267694
2023-01-03 -0.403999  0.496314       NaN  1.585226
2023-01-04 -0.725328  1.423956 -0.669006  0.128995
2023-01-05  0.891227 -0.083633 -1.769143  0.243666

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.419660 -0.834225  0.064101 -0.678894
2023-01-02  0.735682 -0.378234  1.069263  0.267694
2023-01-03 -0.403999  0.496314       NaN  1.585226
2023-01-04 -0.725328  1.423956 -0.669006  0.128995
2023-01-05  0.891227 -0.083633 -1.769143  0.243666

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0  0.580874 -0.363805  0.793712
1 -0.094328  0.710629  0.257290
2 -0.639579  0.594240  0.342541
3 -1.469170 -0.337919  0.961517
4 -1.124253 -1.652260 -0.821521

In [17]:
df_max_min.idxmax(axis=0)

A    0
B    1
C    3
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    B
1    A
2    A
3    A
4    B
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([3, 0, 2, 5, 0, 0, 0, 1, 0, 5, 3, 1, 3, 1, 4, 3, 1, 6, 2, 4, 6, 5,
       4, 4, 3, 1, 2, 2, 4, 1, 4, 3, 0, 2, 6, 1, 0, 6, 1, 2, 6, 0, 5, 2,
       2, 4, 6, 6, 0, 5], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

0    9
2    8
1    8
6    7
4    7
3    6
5    5
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  3  4  2
1  3  4  3
2  0  1  3
3  0  0  0

In [28]:
df_apply.apply(np.sum, axis=0)

A    6
B    9
C    8
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    6    3    0
B    9    4    0
C    8    3    0

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [30]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  7  9  4
2000-01-02  4  4  8
2000-01-03  7  4  5
2000-01-04  3  9  3
2000-01-05  4  9  6
2000-01-06  9  5  7
2000-01-07  9  7  4
2000-01-08  5  3  8
2000-01-09  3  4  7
2000-01-10  9  3  4

In [31]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  2.645751  8  16
2000-01-02  2.000000  3  64
2000-01-03  2.645751  3  25
2000-01-04  1.732051  8   9
2000-01-05  2.000000  8  36
2000-01-06  3.000000  4  49
2000-01-07  3.000000  6  16
2000-01-08  2.236068  2  64
2000-01-09  1.732051  3  49
2000-01-10  3.000000  2  16

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [32]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a    0.048123
b   -1.008707
c    0.409668
d    0.350816
e   -1.286510
dtype: float64

In [33]:
s.reindex(["e", "d", "a"])

e   -1.286510
d    0.350816
a    0.048123
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [34]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [35]:
ts

2000-01-03   -0.117455
2000-01-04    0.333277
2000-01-05    0.623445
2000-01-06    0.656031
2000-01-07   -1.489475
2000-01-08   -1.287829
2000-01-09    0.044485
2000-01-10   -1.100188
Freq: D, dtype: float64

In [36]:
ts2.reindex(ts.index)

2000-01-03   -0.117455
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    0.656031
2000-01-07         NaN
2000-01-08         NaN
2000-01-09    0.044485
2000-01-10         NaN
Freq: D, dtype: float64

In [37]:
ts2.reindex(rng, method="nearest")

2000-01-03   -0.117455
2000-01-04   -0.117455
2000-01-05    0.656031
2000-01-06    0.656031
2000-01-07    0.656031
2000-01-08    0.044485
2000-01-09    0.044485
2000-01-10    0.044485
Freq: D, dtype: float64

### Dropping Labels from an axis

In [38]:
df_drop = pd.DataFrame(np.random.randn(5, 7), columns=["A", "B", "C", "D", "E", "F", "G"])
df_drop

          A         B         C         D         E         F         G
0 -0.406889  0.960876 -0.987753 -0.412572  0.371109 -0.870429  0.907212
1 -3.150079 -0.498804 -0.253532 -0.381392 -1.128908  1.414114  0.643606
2  1.696926 -0.458246 -0.617157  0.348395  0.097824 -0.055840  0.700929
3  0.577112 -0.145509 -0.065248  0.217202 -1.424917 -0.498029  0.094746
4  0.253881  0.905456 -0.232793 -1.147300 -0.609952 -0.572202 -1.047137

In [39]:
# Drop columns
df_drop_columns = df_drop.drop(["B", "D"], axis=1)
df_drop_columns

          A         C         E         F         G
0 -0.406889 -0.987753  0.371109 -0.870429  0.907212
1 -3.150079 -0.253532 -1.128908  1.414114  0.643606
2  1.696926 -0.617157  0.097824 -0.055840  0.700929
3  0.577112 -0.065248 -1.424917 -0.498029  0.094746
4  0.253881 -0.232793 -0.609952 -0.572202 -1.047137

In [40]:
# Drop rows
df_drop_rows = df_drop.drop([0, 1], axis=0)
df_drop_rows

          A         B         C         D         E         F         G
2  1.696926 -0.458246 -0.617157  0.348395  0.097824 -0.055840  0.700929
3  0.577112 -0.145509 -0.065248  0.217202 -1.424917 -0.498029  0.094746
4  0.253881  0.905456 -0.232793 -1.147300 -0.609952 -0.572202 -1.047137

### iterrows

- It allows to iterate through the rows of a DataFrame as Series objects.

In [41]:
df_iterrows = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_iterrows

          A         B         C
0 -1.226158 -0.667119  1.039523
1  0.000322 -1.463392 -0.152323
2  0.045558 -0.879405  0.433804
3 -0.067705  0.335728 -1.137571
4 -1.305119 -0.187382  1.081541

In [42]:
for index, row in df_iterrows.iterrows():
    print(f"Index: {index}")
    print(f"Row A value: {row['A']}")
    print(f"Row B value: {row['B']}")
    print(f"Row C value: {row['C']}")
    print("-----")

Index: 0
Row A value: -1.226158449614631
Row B value: -0.667119153838039
Row C value: 1.0395228764098148
-----
Index: 1
Row A value: 0.0003215651091983421
Row B value: -1.4633917219737234
Row C value: -0.1523232623226409
-----
Index: 2
Row A value: 0.045558339417385636
Row B value: -0.8794053849114453
Row C value: 0.433804470071866
-----
Index: 3
Row A value: -0.06770482849660887
Row B value: 0.3357277450826333
Row C value: -1.1375705792436586
-----
Index: 4
Row A value: -1.3051193816085656
Row B value: -0.18738176217215302
Row C value: 1.0815411616728539
-----

### itertuples

- It will return an iterator yielding a namedtuple for each row in the DataFrame.

In [43]:
df_itertuple = pd.DataFrame(np.random.rand(3, 2), columns=["A", "B"])
df_itertuple

          A         B
0  0.093365  0.206826
1  0.114609  0.812601
2  0.545069  0.553007

In [44]:
for row in df_itertuple.itertuples():
    print(row)

Pandas(Index=0, A=0.09336505038918586, B=0.2068263829635809)
Pandas(Index=1, A=0.11460851237864023, B=0.81260125866137)
Pandas(Index=2, A=0.5450687801266654, B=0.5530069055448456)

#### strftime

- It's a method used in programming (especially in Python) to convert a date/time into a nicely formatted string.

In [45]:
df_strftime = pd.Series(pd.period_range("20130101", periods=4))
df_strftime

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [46]:
df_strftime.dt.strftime('%Y-%m-%d')

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: object

In [48]:
df_strftime.dt.year

0    2013
1    2013
2    2013
3    2013
dtype: int64

In [50]:
df_strftime.dt.day

0    1
1    2
2    3
3    4
dtype: int64