##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [34]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [35]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -0.173756
1   -0.359891
2    0.315687
3    0.000819
4   -1.139020
5   -0.358257
6    1.822440
7    0.123754
8    0.214935
9   -0.608366
dtype: float64

In [36]:
# Head
long_series.head()

0   -0.173756
1   -0.359891
2    0.315687
3    0.000819
4   -1.139020
dtype: float64

In [37]:
# Tail
long_series.tail()

5   -0.358257
6    1.822440
7    0.123754
8    0.214935
9   -0.608366
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [38]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01 -0.664115 -1.055500  0.851626  1.796025
2023-01-02 -0.954483 -1.000656  0.859977 -0.235665
2023-01-03  2.083060 -0.516127  0.966423 -0.903459
2023-01-04 -1.042017  1.042356 -0.924535 -0.441905
2023-01-05 -2.275840 -1.459662  0.738618 -0.275959
2023-01-06 -0.496163  0.875542  0.456205 -0.501123
2023-01-07  0.745660 -0.775909 -0.946606  0.529155
2023-01-08  0.558486 -0.162794  1.368365 -0.384905
2023-01-09 -1.576256 -0.091645 -0.106904 -1.374820
2023-01-10 -0.888852  2.069227  2.226257 -1.838536

In [39]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01 -0.664115 -1.055500  0.851626  1.796025
2023-01-02 -0.954483 -1.000656  0.859977 -0.235665
2023-01-03  2.083060 -0.516127  0.966423 -0.903459
2023-01-04 -1.042017  1.042356 -0.924535 -0.441905
2023-01-05 -2.275840 -1.459662  0.738618 -0.275959
2023-01-06 -0.496163  0.875542  0.456205 -0.501123
2023-01-07  0.745660 -0.775909 -0.946606  0.529155
2023-01-08  0.558486 -0.162794  1.368365 -0.384905
2023-01-09 -1.576256 -0.091645 -0.106904 -1.374820
2023-01-10 -0.888852  2.069227  2.226257 -1.838536

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [40]:
df_numpy = df.to_numpy()
df_numpy

array([[-0.66411508, -1.05549974,  0.85162633,  1.79602485],
       [-0.95448256, -1.00065592,  0.85997725, -0.23566484],
       [ 2.08305953, -0.51612662,  0.96642335, -0.90345868],
       [-1.04201703,  1.04235611, -0.92453463, -0.44190478],
       [-2.27583997, -1.45966158,  0.7386175 , -0.27595909],
       [-0.49616294,  0.87554178,  0.45620506, -0.50112264],
       [ 0.74565969, -0.77590859, -0.94660631,  0.52915523],
       [ 0.5584859 , -0.16279433,  1.3683651 , -0.3849054 ],
       [-1.57625624, -0.09164491, -0.10690406, -1.37481978],
       [-0.88885153,  2.0692271 ,  2.22625651, -1.8385357 ]])

## Flexible binary operations

### Matching / broadcasting behavior

In [41]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  4.0  6.0      1
b  8.0  4.0      0
c  9.0  9.0      1
d  NaN  NaN      8

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [42]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      9.0
two      9.0
three    1.0
Name: c, dtype: float64

In [43]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -5.0 -3.0    0.0
b -1.0 -5.0   -1.0
c  0.0  0.0    0.0
d  NaN  NaN    7.0

### Missing data / operations with fill values

In [44]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01 -0.664115 -1.055500  0.851626  1.796025
2023-01-02 -0.954483 -1.000656  0.859977 -0.235665
2023-01-03  2.083060 -0.516127       NaN -0.903459
2023-01-04 -1.042017  1.042356 -0.924535 -0.441905
2023-01-05 -2.275840 -1.459662  0.738618 -0.275959

In [45]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01 -0.664115 -1.055500  0.851626  1.796025
2023-01-02 -0.954483 -1.000656  0.859977 -0.235665
2023-01-03  2.083060 -0.516127       NaN -0.903459
2023-01-04 -1.042017  1.042356 -0.924535 -0.441905
2023-01-05 -2.275840 -1.459662  0.738618 -0.275959

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [46]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [47]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [48]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [49]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0  0.531544 -0.259663 -0.466860
1  1.683285  1.222144 -1.443447
2  0.123521  2.109516 -2.529673
3 -0.608576  0.058058  0.818456
4  1.382984  0.117401 -1.697660

In [50]:
df_max_min.idxmax(axis=0)

A    1
B    2
C    3
dtype: int64

In [51]:
df_max_min.idxmin(axis=1)

0    C
1    C
2    C
3    A
4    C
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [52]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([4, 4, 4, 3, 6, 5, 1, 4, 4, 1, 3, 6, 6, 1, 6, 3, 4, 6, 1, 5, 4, 0,
       5, 0, 3, 6, 0, 0, 1, 5, 1, 2, 0, 1, 6, 3, 3, 1, 0, 3, 0, 1, 5, 3,
       5, 6, 4, 5, 2, 2])

In [53]:
s = pd.Series(data_hist_value)

In [54]:
s.value_counts()

1    9
4    8
3    8
6    8
5    7
0    7
2    3
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [55]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [56]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [57]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [58]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [59]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [60]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  1  0  0
1  0  2  3
2  2  2  0
3  0  1  2

In [61]:
df_apply.apply(np.sum, axis=0)

A    3
B    5
C    5
dtype: int64

### Aggregation API

In [62]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    3    2    0
B    5    2    0
C    5    3    0

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [63]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  7  9  8
2000-01-02  8  6  3
2000-01-03  3  6  7
2000-01-04  5  4  7
2000-01-05  5  8  8
2000-01-06  6  3  6
2000-01-07  7  7  3
2000-01-08  8  8  9
2000-01-09  3  4  3
2000-01-10  8  4  4

In [64]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  2.645751  8  64
2000-01-02  2.828427  5   9
2000-01-03  1.732051  5  49
2000-01-04  2.236068  3  49
2000-01-05  2.236068  7  64
2000-01-06  2.449490  2  36
2000-01-07  2.645751  6   9
2000-01-08  2.828427  7  81
2000-01-09  1.732051  3   9
2000-01-10  2.828427  3  16

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [65]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a   -0.023406
b    1.227525
c    0.993915
d    1.792599
e    1.305716
dtype: float64

In [66]:
s.reindex(["e", "d", "a"])

e    1.305716
d    1.792599
a   -0.023406
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [67]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [68]:
ts

2000-01-03    0.890876
2000-01-04   -1.471355
2000-01-05    1.084652
2000-01-06    0.235858
2000-01-07    0.530542
2000-01-08   -1.219476
2000-01-09   -0.174223
2000-01-10   -1.094850
Freq: D, dtype: float64

In [69]:
ts2.reindex(ts.index)

2000-01-03    0.890876
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    0.235858
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -0.174223
2000-01-10         NaN
Freq: D, dtype: float64

In [70]:
ts2.reindex(rng, method="nearest")

2000-01-03    0.890876
2000-01-04    0.890876
2000-01-05    0.235858
2000-01-06    0.235858
2000-01-07    0.235858
2000-01-08   -0.174223
2000-01-09   -0.174223
2000-01-10   -0.174223
Freq: D, dtype: float64

### Dropping Labels from an axis

In [71]:
df_drop = pd.DataFrame(np.random.randn(5, 7), columns=["A", "B", "C", "D", "E", "F", "G"])
df_drop

          A         B         C         D         E         F         G
0 -0.943724  1.027481  0.363876  0.725792 -0.104558  0.482751 -0.518800
1  0.752356 -0.107895 -1.207549 -0.573388 -0.426737  0.986243 -0.399030
2  0.498884 -1.301571  0.619465 -0.598735  0.094174 -0.653722  0.342985
3  1.525783  0.101603  0.697121  0.375997  0.291164 -1.390309  0.423728
4  0.862858 -1.263165  0.720032 -0.129374  0.052964  1.054927 -1.019042

In [72]:
# Drop columns
df_drop_columns = df_drop.drop(["B", "D"], axis=1)
df_drop_columns

          A         C         E         F         G
0 -0.943724  0.363876 -0.104558  0.482751 -0.518800
1  0.752356 -1.207549 -0.426737  0.986243 -0.399030
2  0.498884  0.619465  0.094174 -0.653722  0.342985
3  1.525783  0.697121  0.291164 -1.390309  0.423728
4  0.862858  0.720032  0.052964  1.054927 -1.019042

In [73]:
# Drop rows
df_drop_rows = df_drop.drop([0, 1], axis=0)
df_drop_rows

          A         B         C         D         E         F         G
2  0.498884 -1.301571  0.619465 -0.598735  0.094174 -0.653722  0.342985
3  1.525783  0.101603  0.697121  0.375997  0.291164 -1.390309  0.423728
4  0.862858 -1.263165  0.720032 -0.129374  0.052964  1.054927 -1.019042

### iterrows

- It allows to iterate through the rows of a DataFrame as Series objects.

In [74]:
df_iterrows = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_iterrows

          A         B         C
0 -1.415183 -0.802385  0.608380
1 -0.266687 -2.090160 -1.389795
2  1.168938 -1.135902 -0.598112
3  1.011658  0.102526 -0.204491
4  1.228433  0.165296 -0.350994

In [75]:
for index, row in df_iterrows.iterrows():
    print(f"Index: {index}")
    print(f"Row A value: {row['A']}")
    print(f"Row B value: {row['B']}")
    print(f"Row C value: {row['C']}")
    print("-----")

Index: 0
Row A value: -1.4151832909947606
Row B value: -0.8023852630173641
Row C value: 0.6083801637748633
-----
Index: 1
Row A value: -0.2666871242636329
Row B value: -2.090160454710245
Row C value: -1.389795374991674
-----
Index: 2
Row A value: 1.1689376011568098
Row B value: -1.135902468908416
Row C value: -0.5981123848996311
-----
Index: 3
Row A value: 1.011657502922234
Row B value: 0.10252624387157404
Row C value: -0.2044910959857864
-----
Index: 4
Row A value: 1.2284334990077115
Row B value: 0.16529596461703944
Row C value: -0.350994296296739
-----

### itertuples

- It will return an iterator yielding a namedtuple for each row in the DataFrame.

In [78]:
df_itertuple = pd.DataFrame(np.random.rand(3, 2), columns=["A", "B"])
df_itertuple

          A        B
0  0.901016  0.15156
1  0.365059  0.18565
2  0.225822  0.93036

In [79]:
for row in df_itertuple.itertuples():
    print(row)

Pandas(Index=0, A=0.9010161385428741, B=0.15156046083079966)
Pandas(Index=1, A=0.36505914986205024, B=0.18564995208266943)
Pandas(Index=2, A=0.22582202560121512, B=0.930359778482067)