##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0    0.851827
1    0.893343
2    1.228911
3    0.543247
4    0.859643
5    1.411112
6   -1.425830
7   -0.337127
8    0.650750
9    0.164341
dtype: float64

In [3]:
# Head
long_series.head()

0    0.851827
1    0.893343
2    1.228911
3    0.543247
4    0.859643
dtype: float64

In [4]:
# Tail
long_series.tail()

5    1.411112
6   -1.425830
7   -0.337127
8    0.650750
9    0.164341
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.130096  0.583954  0.621541 -1.234418
2023-01-02  0.447585  2.256013 -1.005747  0.215864
2023-01-03 -0.421496  1.824197 -0.342123  0.266125
2023-01-04  0.199811  1.317305 -2.350120  0.440829
2023-01-05  0.225158  0.664401  0.256540  0.016456
2023-01-06 -0.205948  0.519744  3.389498 -1.022705
2023-01-07 -0.325666  0.488016 -0.441786  0.419312
2023-01-08  0.508734 -2.007044  0.530382  0.809624
2023-01-09  0.794927 -1.646884  0.501284  0.299163
2023-01-10  1.206092 -1.094310 -0.318641 -0.871910

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.130096  0.583954  0.621541 -1.234418
2023-01-02  0.447585  2.256013 -1.005747  0.215864
2023-01-03 -0.421496  1.824197 -0.342123  0.266125
2023-01-04  0.199811  1.317305 -2.350120  0.440829
2023-01-05  0.225158  0.664401  0.256540  0.016456
2023-01-06 -0.205948  0.519744  3.389498 -1.022705
2023-01-07 -0.325666  0.488016 -0.441786  0.419312
2023-01-08  0.508734 -2.007044  0.530382  0.809624
2023-01-09  0.794927 -1.646884  0.501284  0.299163
2023-01-10  1.206092 -1.094310 -0.318641 -0.871910

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[ 0.13009606,  0.58395398,  0.62154077, -1.234418  ],
       [ 0.44758504,  2.25601344, -1.00574745,  0.21586402],
       [-0.42149558,  1.82419691, -0.3421233 ,  0.26612457],
       [ 0.19981139,  1.31730526, -2.35011957,  0.44082941],
       [ 0.22515803,  0.66440075,  0.25653989,  0.01645597],
       [-0.2059483 ,  0.51974395,  3.38949813, -1.02270488],
       [-0.32566633,  0.48801555, -0.44178614,  0.41931215],
       [ 0.50873408, -2.00704429,  0.53038182,  0.80962412],
       [ 0.79492696, -1.64688433,  0.50128445,  0.29916254],
       [ 1.20609221, -1.09430975, -0.3186407 , -0.87191015]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  4.0  5.0      2
b  9.0  4.0      3
c  8.0  9.0      5
d  NaN  NaN      3

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      8.0
two      9.0
three    5.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -4.0 -4.0   -3.0
b  1.0 -5.0   -2.0
c  0.0  0.0    0.0
d  NaN  NaN   -2.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.130096  0.583954  0.621541 -1.234418
2023-01-02  0.447585  2.256013 -1.005747  0.215864
2023-01-03 -0.421496  1.824197       NaN  0.266125
2023-01-04  0.199811  1.317305 -2.350120  0.440829
2023-01-05  0.225158  0.664401  0.256540  0.016456

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.130096  0.583954  0.621541 -1.234418
2023-01-02  0.447585  2.256013 -1.005747  0.215864
2023-01-03 -0.421496  1.824197       NaN  0.266125
2023-01-04  0.199811  1.317305 -2.350120  0.440829
2023-01-05  0.225158  0.664401  0.256540  0.016456

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0  0.206219  0.905172 -0.589349
1 -1.296950  1.758829  1.207947
2  1.722460  2.317959  0.515147
3  0.929615 -1.305319 -0.712288
4 -1.037473  0.582746 -0.328454

In [17]:
df_max_min.idxmax(axis=0)

A    2
B    2
C    1
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    C
1    A
2    C
3    B
4    A
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([0, 2, 1, 1, 1, 0, 6, 6, 3, 3, 2, 3, 1, 6, 4, 1, 2, 5, 3, 6, 5, 4,
       1, 1, 1, 4, 1, 3, 2, 2, 2, 6, 6, 2, 2, 5, 3, 5, 4, 0, 2, 4, 0, 3,
       0, 3, 3, 2, 4, 0], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

2    10
1     9
3     9
0     6
6     6
4     6
5     4
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  2  0  4
1  3  1  2
2  2  4  4
3  4  0  2

In [28]:
df_apply.apply(np.sum, axis=0)

A    11
B     5
C    12
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A   11    4    2
B    5    4    0
C   12    4    2

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [30]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  5  6  3
2000-01-02  5  7  8
2000-01-03  7  5  3
2000-01-04  7  6  8
2000-01-05  7  4  6
2000-01-06  5  9  4
2000-01-07  8  3  7
2000-01-08  7  4  4
2000-01-09  6  3  9
2000-01-10  4  5  9

In [31]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  2.236068  5   9
2000-01-02  2.236068  6  64
2000-01-03  2.645751  4   9
2000-01-04  2.645751  5  64
2000-01-05  2.645751  3  36
2000-01-06  2.236068  8  16
2000-01-07  2.828427  2  49
2000-01-08  2.645751  3  16
2000-01-09  2.449490  2  81
2000-01-10  2.000000  4  81

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [32]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a    0.776735
b    1.391930
c    1.045217
d   -1.736126
e    2.202827
dtype: float64

In [33]:
s.reindex(["e", "d", "a"])

e    2.202827
d   -1.736126
a    0.776735
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [34]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [35]:
ts

2000-01-03   -0.653464
2000-01-04   -0.042722
2000-01-05   -1.361357
2000-01-06    0.597628
2000-01-07    0.328096
2000-01-08   -0.164487
2000-01-09    0.268501
2000-01-10   -0.014525
Freq: D, dtype: float64

In [36]:
ts2.reindex(ts.index)

2000-01-03   -0.653464
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    0.597628
2000-01-07         NaN
2000-01-08         NaN
2000-01-09    0.268501
2000-01-10         NaN
Freq: D, dtype: float64

In [37]:
ts2.reindex(rng, method="nearest")

2000-01-03   -0.653464
2000-01-04   -0.653464
2000-01-05    0.597628
2000-01-06    0.597628
2000-01-07    0.597628
2000-01-08    0.268501
2000-01-09    0.268501
2000-01-10    0.268501
Freq: D, dtype: float64

### Dropping Labels from an axis

In [38]:
df_drop = pd.DataFrame(np.random.randn(5, 7), columns=["A", "B", "C", "D", "E", "F", "G"])
df_drop

          A         B         C         D         E         F         G
0  1.461908 -2.858050 -0.757498 -0.922950  0.482610  0.031775  0.701629
1  0.086496  0.030907  0.306930  2.673040 -0.556755 -0.572248 -0.592725
2 -0.342226 -0.560845  1.174510 -0.866617 -1.228065  1.113874 -1.223400
3  0.179199 -0.990343 -0.607834 -0.465086 -1.431496 -0.694053  0.720411
4 -1.509744  0.119111 -0.835630 -1.206260  0.359244  1.039295 -1.060329

In [39]:
# Drop columns
df_drop_columns = df_drop.drop(["B", "D"], axis=1)
df_drop_columns

          A         C         E         F         G
0  1.461908 -0.757498  0.482610  0.031775  0.701629
1  0.086496  0.306930 -0.556755 -0.572248 -0.592725
2 -0.342226  1.174510 -1.228065  1.113874 -1.223400
3  0.179199 -0.607834 -1.431496 -0.694053  0.720411
4 -1.509744 -0.835630  0.359244  1.039295 -1.060329

In [40]:
# Drop rows
df_drop_rows = df_drop.drop([0, 1], axis=0)
df_drop_rows

          A         B         C         D         E         F         G
2 -0.342226 -0.560845  1.174510 -0.866617 -1.228065  1.113874 -1.223400
3  0.179199 -0.990343 -0.607834 -0.465086 -1.431496 -0.694053  0.720411
4 -1.509744  0.119111 -0.835630 -1.206260  0.359244  1.039295 -1.060329

### iterrows

- It allows to iterate through the rows of a DataFrame as Series objects.

In [41]:
df_iterrows = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_iterrows

          A         B         C
0  0.598801 -0.818738 -0.214672
1 -0.977746  0.344970  1.697894
2 -1.644914  0.599905 -0.206444
3 -0.408887 -0.949739 -0.055895
4 -2.401182 -0.291487  0.321820

In [42]:
for index, row in df_iterrows.iterrows():
    print(f"Index: {index}")
    print(f"Row A value: {row['A']}")
    print(f"Row B value: {row['B']}")
    print(f"Row C value: {row['C']}")
    print("-----")

Index: 0
Row A value: 0.598800750609556
Row B value: -0.8187379833773732
Row C value: -0.2146721382678175
-----
Index: 1
Row A value: -0.9777457854469923
Row B value: 0.3449696801763144
Row C value: 1.6978938760856173
-----
Index: 2
Row A value: -1.6449141948304047
Row B value: 0.5999045181827605
Row C value: -0.20644446172871628
-----
Index: 3
Row A value: -0.40888707508151195
Row B value: -0.9497385426554781
Row C value: -0.05589476114764196
-----
Index: 4
Row A value: -2.4011815042145352
Row B value: -0.2914873717303877
Row C value: 0.3218198025182049
-----

### itertuples

- It will return an iterator yielding a namedtuple for each row in the DataFrame.

In [43]:
df_itertuple = pd.DataFrame(np.random.rand(3, 2), columns=["A", "B"])
df_itertuple

          A         B
0  0.015883  0.487519
1  0.296733  0.211411
2  0.530797  0.677379

In [44]:
for row in df_itertuple.itertuples():
    print(row)

Pandas(Index=0, A=0.01588256739288918, B=0.48751856973706686)
Pandas(Index=1, A=0.2967327590548997, B=0.21141133059828443)
Pandas(Index=2, A=0.5307973869362321, B=0.6773794429684028)

#### strftime

- It's a method used in programming (especially in Python) to convert a date/time into a nicely formatted string.

In [45]:
df_strftime = pd.Series(pd.period_range("20130101", periods=4))
df_strftime

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [46]:
df_strftime.dt.strftime('%Y-%m-%d')

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: object

In [47]:
df_strftime.dt.year

0    2013
1    2013
2    2013
3    2013
dtype: int64

In [48]:
df_strftime.dt.day

0    1
1    2
2    3
3    4
dtype: int64

## Sorting

In [69]:
s1 = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3], "c": [2, 3, 4]}).set_index(
    list("ab")
)
s1

     c
a b
B 1  2
a 2  3
C 3  4

In [70]:
s1.sort_index(level="a")

     c
a b
B 1  2
C 3  4
a 2  3