##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -0.744457
1   -0.191770
2   -0.186233
3    0.956223
4   -0.451710
5   -0.088041
6    0.104666
7   -0.616668
8   -0.015176
9   -0.943244
dtype: float64

In [3]:
# Head
long_series.head()

0   -0.744457
1   -0.191770
2   -0.186233
3    0.956223
4   -0.451710
dtype: float64

In [4]:
# Tail
long_series.tail()

5   -0.088041
6    0.104666
7   -0.616668
8   -0.015176
9   -0.943244
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.222468  1.207972 -1.793313  1.000488
2023-01-02  0.282941 -0.112261  0.555934 -0.876519
2023-01-03  1.483654  0.690296  2.402811 -1.117382
2023-01-04 -0.820965 -0.085249  0.000834 -1.542032
2023-01-05 -0.669407  0.554492  0.155319 -0.812919
2023-01-06  1.079541  0.280252  0.683557  0.346623
2023-01-07  0.829930 -1.314391 -0.939678  0.982882
2023-01-08  0.806620  1.641138 -1.976496  0.038825
2023-01-09  0.674538 -0.181751 -0.803083  0.395061
2023-01-10 -1.470564  0.598724  0.496515 -0.733789

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.222468  1.207972 -1.793313  1.000488
2023-01-02  0.282941 -0.112261  0.555934 -0.876519
2023-01-03  1.483654  0.690296  2.402811 -1.117382
2023-01-04 -0.820965 -0.085249  0.000834 -1.542032
2023-01-05 -0.669407  0.554492  0.155319 -0.812919
2023-01-06  1.079541  0.280252  0.683557  0.346623
2023-01-07  0.829930 -1.314391 -0.939678  0.982882
2023-01-08  0.806620  1.641138 -1.976496  0.038825
2023-01-09  0.674538 -0.181751 -0.803083  0.395061
2023-01-10 -1.470564  0.598724  0.496515 -0.733789

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[ 2.22468377e-01,  1.20797212e+00, -1.79331308e+00,
         1.00048839e+00],
       [ 2.82940961e-01, -1.12261405e-01,  5.55933972e-01,
        -8.76519346e-01],
       [ 1.48365442e+00,  6.90295538e-01,  2.40281124e+00,
        -1.11738183e+00],
       [-8.20964960e-01, -8.52491430e-02,  8.34480714e-04,
        -1.54203216e+00],
       [-6.69406924e-01,  5.54492334e-01,  1.55319318e-01,
        -8.12918702e-01],
       [ 1.07954134e+00,  2.80251797e-01,  6.83557194e-01,
         3.46623168e-01],
       [ 8.29930087e-01, -1.31439105e+00, -9.39677620e-01,
         9.82881549e-01],
       [ 8.06620359e-01,  1.64113809e+00, -1.97649589e+00,
         3.88253902e-02],
       [ 6.74537921e-01, -1.81751399e-01, -8.03082873e-01,
         3.95061383e-01],
       [-1.47056382e+00,  5.98724086e-01,  4.96515064e-01,
        -7.33789422e-01]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  1.0  2.0      6
b  4.0  5.0      1
c  8.0  5.0      9
d  NaN  NaN      2

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      8.0
two      5.0
three    9.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a -7.0 -3.0   -3.0
b -4.0  0.0   -8.0
c  0.0  0.0    0.0
d  NaN  NaN   -7.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.222468  1.207972 -1.793313  1.000488
2023-01-02  0.282941 -0.112261  0.555934 -0.876519
2023-01-03  1.483654  0.690296       NaN -1.117382
2023-01-04 -0.820965 -0.085249  0.000834 -1.542032
2023-01-05 -0.669407  0.554492  0.155319 -0.812919

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.222468  1.207972 -1.793313  1.000488
2023-01-02  0.282941 -0.112261  0.555934 -0.876519
2023-01-03  1.483654  0.690296       NaN -1.117382
2023-01-04 -0.820965 -0.085249  0.000834 -1.542032
2023-01-05 -0.669407  0.554492  0.155319 -0.812919

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0  0.664820 -1.726638 -0.812160
1  0.086524 -0.009533 -0.218917
2  0.776804  0.606469 -0.762564
3 -0.371150 -0.355421 -0.881735
4  1.112884  0.852801 -0.548041

In [17]:
df_max_min.idxmax(axis=0)

A    4
B    4
C    1
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    B
1    C
2    C
3    C
4    C
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([6, 5, 1, 5, 6, 1, 0, 1, 2, 6, 3, 4, 3, 5, 5, 5, 0, 4, 3, 1, 5, 5,
       0, 5, 1, 4, 6, 0, 5, 0, 5, 4, 0, 2, 1, 0, 2, 1, 1, 5, 5, 0, 3, 1,
       2, 6, 3, 5, 0, 0], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

5    13
0    10
1     9
6     5
3     5
2     4
4     4
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  0  3  0
1  4  1  3
2  2  2  0
3  1  4  1

In [28]:
df_apply.apply(np.sum, axis=0)

A     7
B    10
C     4
dtype: int64

### Aggregation API

In [33]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    7    4    0
B   10    4    1
C    4    3    0