##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [2]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [3]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -0.614448
1    1.112233
2   -0.713895
3    0.287507
4   -1.060574
5   -0.172333
6    1.427108
7    0.491065
8    0.756968
9    0.701864
dtype: float64

In [4]:
# Head
long_series.head()

0   -0.614448
1    1.112233
2   -0.713895
3    0.287507
4   -1.060574
dtype: float64

In [5]:
# Tail
long_series.tail()

5   -0.172333
6    1.427108
7    0.491065
8    0.756968
9    0.701864
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [6]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.450564 -0.230651  0.949672 -0.440181
2023-01-02 -1.669092  0.181172  1.580302  0.987796
2023-01-03  0.243473 -0.864292  0.128649 -0.020497
2023-01-04 -0.461213 -1.940929  1.094718 -2.024068
2023-01-05 -0.366770  0.110957  0.231932  0.978189
2023-01-06 -0.179412 -0.853761  0.419680  0.373389
2023-01-07 -0.471778  1.156893  0.060379 -1.136974
2023-01-08  1.206404 -1.655295  0.741566 -1.533236
2023-01-09  0.921974  0.400926  1.269955  0.276954
2023-01-10 -0.755348 -0.093382  0.036780 -1.210183

In [7]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.450564 -0.230651  0.949672 -0.440181
2023-01-02 -1.669092  0.181172  1.580302  0.987796
2023-01-03  0.243473 -0.864292  0.128649 -0.020497
2023-01-04 -0.461213 -1.940929  1.094718 -2.024068
2023-01-05 -0.366770  0.110957  0.231932  0.978189
2023-01-06 -0.179412 -0.853761  0.419680  0.373389
2023-01-07 -0.471778  1.156893  0.060379 -1.136974
2023-01-08  1.206404 -1.655295  0.741566 -1.533236
2023-01-09  0.921974  0.400926  1.269955  0.276954
2023-01-10 -0.755348 -0.093382  0.036780 -1.210183

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [8]:
df_numpy = df.to_numpy()
df_numpy

array([[ 0.45056418, -0.23065132,  0.94967215, -0.44018133],
       [-1.6690918 ,  0.1811718 ,  1.58030156,  0.987796  ],
       [ 0.24347292, -0.86429181,  0.12864921, -0.02049667],
       [-0.46121297, -1.94092851,  1.09471846, -2.02406767],
       [-0.36677015,  0.11095664,  0.23193153,  0.97818948],
       [-0.17941216, -0.85376148,  0.41968023,  0.37338916],
       [-0.4717779 ,  1.15689301,  0.06037901, -1.1369742 ],
       [ 1.20640419, -1.65529471,  0.74156649, -1.53323615],
       [ 0.92197449,  0.4009259 ,  1.26995532,  0.27695414],
       [-0.75534759, -0.0933816 ,  0.03678046, -1.21018275]])

## Flexible binary operations

### Matching / broadcasting behavior

In [9]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  4.0  5.0      9
b  4.0  0.0      2
c  3.0  2.0      7
d  NaN  NaN      5

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [10]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      3.0
two      2.0
three    7.0
Name: c, dtype: float64

In [11]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a  1.0  3.0    2.0
b  1.0 -2.0   -5.0
c  0.0  0.0    0.0
d  NaN  NaN   -2.0

### Missing data / operations with fill values

In [12]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.450564 -0.230651  0.949672 -0.440181
2023-01-02 -1.669092  0.181172  1.580302  0.987796
2023-01-03  0.243473 -0.864292       NaN -0.020497
2023-01-04 -0.461213 -1.940929  1.094718 -2.024068
2023-01-05 -0.366770  0.110957  0.231932  0.978189

In [13]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.450564 -0.230651  0.949672 -0.440181
2023-01-02 -1.669092  0.181172  1.580302  0.987796
2023-01-03  0.243473 -0.864292       NaN -0.020497
2023-01-04 -0.461213 -1.940929  1.094718 -2.024068
2023-01-05 -0.366770  0.110957  0.231932  0.978189

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [14]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [15]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [16]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [17]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0  2.005083 -0.421135  0.042001
1 -0.067538 -0.027471 -0.635003
2 -0.012894  0.785575 -1.386017
3  1.272084 -1.059467 -0.063662
4 -0.803434  2.334720 -0.024823

In [18]:
df_max_min.idxmax(axis=0)

A    0
B    4
C    0
dtype: int64

In [19]:
df_max_min.idxmin(axis=1)

0    B
1    C
2    C
3    B
4    A
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [20]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([4, 2, 4, 5, 1, 0, 2, 5, 3, 1, 2, 5, 1, 5, 1, 5, 5, 0, 4, 5, 5, 1,
       4, 4, 0, 3, 3, 1, 1, 5, 3, 2, 0, 1, 0, 0, 2, 3, 0, 6, 6, 2, 5, 0,
       4, 6, 1, 3, 4, 6])

In [21]:
s = pd.Series(data_hist_value)

In [22]:
s.value_counts()

5    10
1     9
0     8
4     7
2     6
3     6
6     4
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [23]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [24]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [25]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [26]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [27]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [28]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  2  3  4
1  1  2  0
2  2  0  1
3  1  1  0

In [29]:
df_apply.apply(np.sum, axis=0)

A    6
B    6
C    5
dtype: int64

### Aggregation API

In [30]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    6    2    1
B    6    3    0
C    5    4    0

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [31]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  5  9  5
2000-01-02  3  3  3
2000-01-03  9  7  6
2000-01-04  4  7  9
2000-01-05  5  9  5
2000-01-06  6  9  3
2000-01-07  9  8  9
2000-01-08  5  8  9
2000-01-09  6  8  8
2000-01-10  3  6  8

In [32]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  2.236068  8  25
2000-01-02  1.732051  2   9
2000-01-03  3.000000  6  36
2000-01-04  2.000000  6  81
2000-01-05  2.236068  8  25
2000-01-06  2.449490  8   9
2000-01-07  3.000000  7  81
2000-01-08  2.236068  7  81
2000-01-09  2.449490  7  64
2000-01-10  1.732051  5  64

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [33]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a   -1.913136
b    1.452469
c    0.998887
d    0.688946
e   -0.055638
dtype: float64

In [34]:
s.reindex(["e", "d", "a"])

e   -0.055638
d    0.688946
a   -1.913136
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [35]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [36]:
ts

2000-01-03   -0.109287
2000-01-04   -1.336922
2000-01-05   -0.422620
2000-01-06    0.061137
2000-01-07    0.057902
2000-01-08   -1.657184
2000-01-09    0.181332
2000-01-10    0.016752
Freq: D, dtype: float64

In [37]:
ts2.reindex(ts.index)

2000-01-03   -0.109287
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    0.061137
2000-01-07         NaN
2000-01-08         NaN
2000-01-09    0.181332
2000-01-10         NaN
Freq: D, dtype: float64

In [38]:
ts2.reindex(rng, method="nearest")

2000-01-03   -0.109287
2000-01-04   -0.109287
2000-01-05    0.061137
2000-01-06    0.061137
2000-01-07    0.061137
2000-01-08    0.181332
2000-01-09    0.181332
2000-01-10    0.181332
Freq: D, dtype: float64

### Dropping Labels from an axis

In [39]:
df_drop = pd.DataFrame(np.random.randn(5, 7), columns=["A", "B", "C", "D", "E", "F", "G"])
df_drop

          A         B         C         D         E         F         G
0 -0.698300 -1.427093  0.091790  1.790863  0.941274  0.365881  0.424620
1  1.829514 -0.410881 -0.561220 -0.314759  1.766521 -0.274276  0.894968
2 -0.348825 -0.322237  0.509038 -1.505540 -0.133077  0.697184 -1.441929
3  1.382114 -1.068663 -0.249157  0.114829  0.286327  0.543241  0.108701
4 -0.450966 -0.396231 -1.000327  0.153193 -0.025210  0.772571  1.092425

In [40]:
# Drop columns
df_drop_columns = df_drop.drop(["B", "D"], axis=1)
df_drop_columns

          A         C         E         F         G
0 -0.698300  0.091790  0.941274  0.365881  0.424620
1  1.829514 -0.561220  1.766521 -0.274276  0.894968
2 -0.348825  0.509038 -0.133077  0.697184 -1.441929
3  1.382114 -0.249157  0.286327  0.543241  0.108701
4 -0.450966 -1.000327 -0.025210  0.772571  1.092425

In [41]:
# Drop rows
df_drop_rows = df_drop.drop([0, 1], axis=0)
df_drop_rows

          A         B         C         D         E         F         G
2 -0.348825 -0.322237  0.509038 -1.505540 -0.133077  0.697184 -1.441929
3  1.382114 -1.068663 -0.249157  0.114829  0.286327  0.543241  0.108701
4 -0.450966 -0.396231 -1.000327  0.153193 -0.025210  0.772571  1.092425

### iterrows

- It allows to iterate through the rows of a DataFrame as Series objects.

In [42]:
df_iterrows = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_iterrows

          A         B         C
0 -0.681624 -2.088732  1.866710
1 -1.326553 -0.518657 -0.617447
2  0.412376 -0.079417 -0.135472
3  0.587167 -0.868283 -0.940254
4 -1.182227  0.653059  0.051422

In [43]:
for index, row in df_iterrows.iterrows():
    print(f"Index: {index}")
    print(f"Row A value: {row['A']}")
    print(f"Row B value: {row['B']}")
    print(f"Row C value: {row['C']}")
    print("-----")

Index: 0
Row A value: -0.6816235090032309
Row B value: -2.088732285167124
Row C value: 1.8667099085266439
-----
Index: 1
Row A value: -1.3265531083487685
Row B value: -0.5186571052199618
Row C value: -0.6174473152881296
-----
Index: 2
Row A value: 0.4123763827973309
Row B value: -0.07941723291750527
Row C value: -0.1354716892161106
-----
Index: 3
Row A value: 0.5871668129955183
Row B value: -0.8682830329279568
Row C value: -0.940253970652608
-----
Index: 4
Row A value: -1.1822272055518266
Row B value: 0.6530592704672132
Row C value: 0.051421649273243414
-----

### itertuples

- It will return an iterator yielding a namedtuple for each row in the DataFrame.

In [44]:
df_itertuple = pd.DataFrame(np.random.rand(3, 2), columns=["A", "B"])
df_itertuple

          A         B
0  0.290903  0.233734
1  0.896379  0.194722
2  0.595317  0.419065

In [45]:
for row in df_itertuple.itertuples():
    print(row)

Pandas(Index=0, A=0.29090348627950047, B=0.2337343614018098)
Pandas(Index=1, A=0.8963792898254528, B=0.19472204365662849)
Pandas(Index=2, A=0.5953174266700855, B=0.4190653697020945)

#### strftime

- It's a method used in programming (especially in Python) to convert a date/time into a nicely formatted string.

In [46]:
df_strftime = pd.Series(pd.period_range("20130101", periods=4))
df_strftime

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [47]:
df_strftime.dt.strftime('%Y-%m-%d')

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: object

In [48]:
df_strftime.dt.year

0    2013
1    2013
2    2013
3    2013
dtype: int64

In [49]:
df_strftime.dt.day

0    1
1    2
2    3
3    4
dtype: int64

## Sorting

In [50]:
s1 = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3], "c": [2, 3, 4]}).set_index(
    list("ab")
)
s1

     c
a b
B 1  2
a 2  3
C 3  4

In [51]:
s1.sort_index(level="a")

     c
a b
B 1  2
C 3  4
a 2  3

### Smallest and Largest

In [52]:
df_sm = pd.Series(np.random.permutation(10))
df_sm

0    7
1    1
2    4
3    6
4    5
5    2
6    8
7    3
8    0
9    9
dtype: int64

In [53]:
df_sm.nsmallest(3)

8    0
1    1
5    2
dtype: int64

In [54]:
df_sm.nlargest(3)

9    9
6    8
0    7
dtype: int64

### astype

In [71]:
df_astype = pd.DataFrame({
    "A": np.random.randint(1,15, size=4),
    "B": pd.Timestamp("20230102"),
    "C": pd.Series(range(4), dtype="float32"),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo",
})
df_astype

   A          B    C  D      E    F
0  3 2023-01-02  0.0  3   test  foo
1  4 2023-01-02  1.0  3  train  foo
2  5 2023-01-02  2.0  3   test  foo
3  6 2023-01-02  3.0  3  train  foo

In [72]:
df_astype.dtypes

A            int64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [75]:
df_astype = df_astype.astype({"A": np.float64, "C": np.float64})
df_astype

     A          B    C  D      E    F
0  3.0 2023-01-02  0.0  3   test  foo
1  4.0 2023-01-02  1.0  3  train  foo
2  5.0 2023-01-02  2.0  3   test  foo
3  6.0 2023-01-02  3.0  3  train  foo

In [76]:
df_astype.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object