##  📚 Essential Basic Functionality

> Pandas is a foundational library in Python for working with structured data. It provides fast, flexible, and expressive tools designed to make data analysis and manipulation easy and intuitive. There are several essential functionalities that are fundamental to using Pandas effectively.

In [1]:
import pandas as pd
import numpy as np

## Accelerated operations

### Head and tail

- Head shows the first 5 rows by default.
- Tail shows the last 5 rows by default.

In [2]:
long_series = pd.Series(np.random.randn(10))
long_series

0   -1.477337
1   -1.789959
2    1.465723
3    1.317940
4    0.244050
5    0.440529
6   -0.203446
7    0.982124
8   -0.622497
9    0.256056
dtype: float64

In [3]:
# Head
long_series.head()

0   -1.477337
1   -1.789959
2    1.465723
3    1.317940
4    0.244050
dtype: float64

In [4]:
# Tail
long_series.tail()

5    0.440529
6   -0.203446
7    0.982124
8   -0.622497
9    0.256056
dtype: float64

### Attributes and underlying data

- shape: gives the axis dimensions of the object, consistent with ndarray
- Axis labels:
    - Series: index (only axis)
    - DataFrame: index and columns

In [5]:
index = pd.date_range('20230101', periods=10)
df = pd.DataFrame(np.random.randn(10, 4), index=index, columns=list ('ABCD'))
df

                   A         B         C         D
2023-01-01  0.938150 -1.811888 -0.703787 -0.341373
2023-01-02  0.711947 -1.166951  1.670242 -0.494183
2023-01-03 -1.297729  0.221283 -0.361184  0.016029
2023-01-04 -0.406407 -1.071781 -0.656687 -1.812831
2023-01-05 -0.620582 -1.724885 -1.468824  0.057476
2023-01-06 -1.062691 -0.612219 -1.536498 -0.569399
2023-01-07 -0.450398  2.061382 -0.045433  1.114122
2023-01-08 -0.651210  0.148864 -1.158412 -0.491609
2023-01-09  0.235964  3.280286 -1.656583 -0.783198
2023-01-10 -0.647647 -0.136076  0.779536 -2.267862

In [6]:
df.columns = [x.lower() for x in df.columns]
df

                   a         b         c         d
2023-01-01  0.938150 -1.811888 -0.703787 -0.341373
2023-01-02  0.711947 -1.166951  1.670242 -0.494183
2023-01-03 -1.297729  0.221283 -0.361184  0.016029
2023-01-04 -0.406407 -1.071781 -0.656687 -1.812831
2023-01-05 -0.620582 -1.724885 -1.468824  0.057476
2023-01-06 -1.062691 -0.612219 -1.536498 -0.569399
2023-01-07 -0.450398  2.061382 -0.045433  1.114122
2023-01-08 -0.651210  0.148864 -1.158412 -0.491609
2023-01-09  0.235964  3.280286 -1.656583 -0.783198
2023-01-10 -0.647647 -0.136076  0.779536 -2.267862

#### Numpy

- It is a reliable and consistent method to convert pandas objects to NumPy arrays, offering better control over data types and compatibility with extension types compared other methods.

In [7]:
df_numpy = df.to_numpy()
df_numpy

array([[ 0.93814987, -1.81188777, -0.70378669, -0.34137342],
       [ 0.71194662, -1.16695066,  1.67024164, -0.49418338],
       [-1.29772904,  0.22128264, -0.36118419,  0.01602855],
       [-0.40640674, -1.07178133, -0.65668718, -1.8128312 ],
       [-0.62058227, -1.72488516, -1.46882383,  0.05747609],
       [-1.06269131, -0.61221927, -1.5364981 , -0.56939875],
       [-0.45039787,  2.06138226, -0.04543344,  1.11412172],
       [-0.65120981,  0.14886422, -1.15841214, -0.49160906],
       [ 0.23596435,  3.28028575, -1.6565825 , -0.78319825],
       [-0.64764664, -0.13607551,  0.77953648, -2.26786241]])

## Flexible binary operations

### Matching / broadcasting behavior

In [8]:
df_mathing_broadcasting = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randint(0, 10, 3), index=["a", "b", "c"]),
        "three": pd.Series(np.random.randint(0, 10, 4), index=["a", "b", "c", "d"]),

    }
)
df_mathing_broadcasting

   one  two  three
a  7.0  2.0      3
b  5.0  3.0      7
c  6.0  9.0      1
d  NaN  NaN      4

### Sub

- It is a method used to perform subtraction between Series or DataFrames.

In [9]:
df_sub_l1 = df_mathing_broadcasting.iloc[2]
df_sub_l1

one      6.0
two      9.0
three    1.0
Name: c, dtype: float64

In [10]:
df_mathing_broadcasting.sub(df_sub_l1 , axis="columns")

   one  two  three
a  1.0 -7.0    2.0
b -1.0 -6.0    6.0
c  0.0  0.0    0.0
d  NaN  NaN    3.0

### Missing data / operations with fill values

In [11]:
df_filldata = df.copy()
df_filldata.iloc[2, 2] = np.nan
df_filldata.head()

                   a         b         c         d
2023-01-01  0.938150 -1.811888 -0.703787 -0.341373
2023-01-02  0.711947 -1.166951  1.670242 -0.494183
2023-01-03 -1.297729  0.221283       NaN  0.016029
2023-01-04 -0.406407 -1.071781 -0.656687 -1.812831
2023-01-05 -0.620582 -1.724885 -1.468824  0.057476

In [12]:
df_filldata.fillna(np.random.rand())
df_filldata.head()

                   a         b         c         d
2023-01-01  0.938150 -1.811888 -0.703787 -0.341373
2023-01-02  0.711947 -1.166951  1.670242 -0.494183
2023-01-03 -1.297729  0.221283       NaN  0.016029
2023-01-04 -0.406407 -1.071781 -0.656687 -1.812831
2023-01-05 -0.620582 -1.724885 -1.468824  0.057476

### Boolean reductions

- It is a way to summarize a boolean result.
-  <code>empty, any(), all(), and bool()</code>

In [13]:
df_bool_reduction = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [0, 0, 5],
    "C": [9, 9, 9]
})

df_bool_reduction

   A  B  C
0  1  0  9
1  2  0  9
2  3  5  9

In [14]:
(df_bool_reduction > 0).all()

A     True
B    False
C     True
dtype: bool

In [15]:
(df_bool_reduction > 0).any()

A    True
B    True
C    True
dtype: bool

## Descriptive statistics

### Index of min/max values

- idxmin = it return index of first occurrence of minimum over requested axis.
- idxmax = it return index of first occurrence of maximum over requested axis.

In [16]:
df_max_min = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df_max_min

          A         B         C
0  0.497470  2.091491  0.202444
1  0.208562 -0.687260 -0.179530
2 -0.244454  0.203473 -0.940551
3  1.691129 -0.948164  0.709267
4  0.772820  1.342857 -0.131131

In [17]:
df_max_min.idxmax(axis=0)

A    3
B    0
C    3
dtype: int64

In [18]:
df_max_min.idxmin(axis=1)

0    C
1    B
2    C
3    B
4    C
dtype: object

### Value counts (histogramming) / mode

- It computes a histogram of a 1D array of values.

In [19]:
data_hist_value = np.random.randint(0, 7, size=50)
data_hist_value

array([2, 1, 2, 5, 2, 6, 3, 2, 3, 5, 2, 0, 5, 4, 4, 5, 5, 4, 1, 5, 2, 4,
       0, 2, 0, 3, 0, 5, 3, 4, 1, 4, 5, 4, 6, 2, 5, 1, 0, 3, 3, 5, 4, 4,
       4, 1, 4, 5, 3, 5], dtype=int32)

In [20]:
s = pd.Series(data_hist_value)

In [21]:
s.value_counts()

5    12
4    11
2     8
3     7
1     5
0     5
6     2
Name: count, dtype: int64

### Discretization and quantiling

- Discretization (pd.cut()): Divides continuous data into fixed-size intervals or bins.
- Quantiling (pd.qcut()): Divides continuous data into equal-sized bins based on quantiles (e.g., quartiles).

In [22]:
arr = [1, 5, 10, 15, 20, 25, 30]
arr

[1, 5, 10, 15, 20, 25, 30]

#### Discretizing

In [23]:
bins = [0, 10, 20, 30]
labels = ['Low', 'Medium', 'High']
result = pd.cut(arr,3)
result

[(0.971, 10.667], (0.971, 10.667], (0.971, 10.667], (10.667, 20.333], (10.667, 20.333], (20.333, 30.0], (20.333, 30.0]]
Categories (3, interval[float64, right]): [(0.971, 10.667] < (10.667, 20.333] < (20.333, 30.0]]

In [24]:
# Discretizing the data into 3 bins
result = pd.cut(arr,3, labels=labels)
result

['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

#### Quantiling

In [25]:
# exact quantile boundaries
result_qcut = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
result_qcut

[(0.999, 7.5], (0.999, 7.5], (7.5, 15.0], (7.5, 15.0], (15.0, 22.5], (22.5, 30.0], (22.5, 30.0]]
Categories (4, interval[float64, right]): [(0.999, 7.5] < (7.5, 15.0] < (15.0, 22.5] < (22.5, 30.0]]

In [26]:
# equal representation in each bin
result_qcut = pd.qcut(arr, 3, labels=['Q1', 'Q2', 'Q3'])
result_qcut

['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q3']
Categories (3, object): ['Q1' < 'Q2' < 'Q3']

## Function application

### Row or column-wise function application

- apply -  Arbitrary functions can be applied along the axes of a DataFrame.

In [27]:
df_apply = pd.DataFrame(np.random.randint(0, 5, (4, 3)), columns=['A', 'B', 'C'])
df_apply

   A  B  C
0  0  2  0
1  4  4  0
2  0  0  3
3  1  2  0

In [28]:
df_apply.apply(np.sum, axis=0)

A    5
B    8
C    3
dtype: int64

### Aggregation API

In [29]:
df_apply.agg(['sum', 'max', 'min'], axis=0).T

   sum  max  min
A    5    4    0
B    8    4    0
C    3    3    0

### Transform

- It allows to provide multiple operations at the same time rather than one-by-one.

In [30]:
tsdf = pd.DataFrame(
    np.random.randint(3, 10, (10, 3)),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10)
)
tsdf

            A  B  C
2000-01-01  9  5  6
2000-01-02  9  6  9
2000-01-03  6  5  5
2000-01-04  5  8  6
2000-01-05  9  7  4
2000-01-06  3  6  5
2000-01-07  5  8  7
2000-01-08  6  6  3
2000-01-09  8  4  9
2000-01-10  7  9  3

In [31]:
tsdf.transform({"A": np.sqrt, "B": lambda x: x-1, "C": lambda x: x**2})

                   A  B   C
2000-01-01  3.000000  4  36
2000-01-02  3.000000  5  81
2000-01-03  2.449490  4  25
2000-01-04  2.236068  7  36
2000-01-05  3.000000  6  16
2000-01-06  1.732051  5  25
2000-01-07  2.236068  7  49
2000-01-08  2.449490  5   9
2000-01-09  2.828427  3  81
2000-01-10  2.645751  8   9

## Reindexing and altering labels

- reindex - It is a conform the data to match a given set of labels along a particular axis.

In [32]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a   -0.706385
b    1.897813
c    0.960200
d    2.085437
e    0.100917
dtype: float64

In [33]:
s.reindex(["e", "d", "a"])

e    0.100917
d    2.085437
a   -0.706385
dtype: float64

### Filling while reindexing

| **Method**            | **Action**                                                                     |
| --------------------- | ------------------------------------------------------------------------------ |
| `pad` or `ffill`      | Fill missing values **forward** (use the last known value)                     |
| `bfill` or `backfill` | Fill missing values **backward** (use the next known value)                    |
| `nearest`             | Fill missing values using the **nearest** valid value based on index proximity |

In [34]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts.iloc[[0, 3, 6]]

In [35]:
ts

2000-01-03   -0.603354
2000-01-04    0.739168
2000-01-05   -0.189935
2000-01-06   -1.315651
2000-01-07   -0.401986
2000-01-08    0.518261
2000-01-09   -1.298758
2000-01-10   -0.133446
Freq: D, dtype: float64

In [36]:
ts2.reindex(ts.index)

2000-01-03   -0.603354
2000-01-04         NaN
2000-01-05         NaN
2000-01-06   -1.315651
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -1.298758
2000-01-10         NaN
Freq: D, dtype: float64

In [37]:
ts2.reindex(rng, method="nearest")

2000-01-03   -0.603354
2000-01-04   -0.603354
2000-01-05   -1.315651
2000-01-06   -1.315651
2000-01-07   -1.315651
2000-01-08   -1.298758
2000-01-09   -1.298758
2000-01-10   -1.298758
Freq: D, dtype: float64

### Dropping Labels from an axis

In [38]:
df_drop = pd.DataFrame(np.random.randn(5, 7), columns=["A", "B", "C", "D", "E", "F", "G"])
df_drop

          A         B         C         D         E         F         G
0 -0.524543 -0.408545 -2.433942 -0.269306  2.021237 -0.339626 -1.037735
1  0.798375  0.502266 -0.322011  1.233159  0.105829  0.037986 -0.291720
2  0.788284  0.645970 -0.079980 -0.949389  1.165879 -0.384837  0.220832
3  0.228205 -0.316009  0.976667  1.401389  0.562394 -0.506600 -1.026581
4  2.109116  0.731175 -0.954065  0.385406  0.694247 -0.262331  0.650062

In [39]:
# Drop columns
df_drop_columns = df_drop.drop(["B", "D"], axis=1)
df_drop_columns

          A         C         E         F         G
0 -0.524543 -2.433942  2.021237 -0.339626 -1.037735
1  0.798375 -0.322011  0.105829  0.037986 -0.291720
2  0.788284 -0.079980  1.165879 -0.384837  0.220832
3  0.228205  0.976667  0.562394 -0.506600 -1.026581
4  2.109116 -0.954065  0.694247 -0.262331  0.650062

In [40]:
# Drop rows
df_drop_rows = df_drop.drop([0, 1], axis=0)
df_drop_rows

          A         B         C         D         E         F         G
2  0.788284  0.645970 -0.079980 -0.949389  1.165879 -0.384837  0.220832
3  0.228205 -0.316009  0.976667  1.401389  0.562394 -0.506600 -1.026581
4  2.109116  0.731175 -0.954065  0.385406  0.694247 -0.262331  0.650062